import XCTest
@testable import GolfMap

/// TS ↔ Swift parity for the ported smart-caddy (`runCaddy` evaluator +
/// `greenSlopeHalfRule`): replays every golden case from the `caddy` section of
/// `strategy-goldens.json` (generated by `shared/strategy/generate-swift-fixtures.ts`)
/// and asserts the Swift mirror reproduces the TS ranking / advice.
///
/// Coverage mirrors run.test.ts + green-slope-half.test.ts: ranking order, veto
/// demote/remove, empty context, risk weighting, deterministic dedupe; the rule
/// firing (aligned steep + clean front), suppressed (front hazard), and no-advice
/// (shallow / cross-slope / front-to-back / wrong leg / missing summary).
final class CaddyGoldenParityTests: XCTestCase {

    private let acc = 1e-9

    /// Concrete club to satisfy the generic context (the caddy ignores clubs).
    private struct DummyClub: ClubSpec {
        var carryM: Double = 0
        var dispersionM: Double = 0
    }

    // MARK: - Fixture schema

    private struct XY: Decodable {
        let x: Double
        let y: Double
        var vec: Vec2 { Vec2(x: x, y: y) }
    }

    private struct RingFx: Decodable {
        let kind: String
        let points: [XY]
        var ring: FlatRing { FlatRing(points: points.map(\.vec), kind: kind) }
    }

    private struct AdviceInput: Decodable {
        let ruleId: String
        let kind: String?
        let priority: Double?
        let confidence: Double?
        let headline: String?
        let detail: String?
        let vetoes: [String]?
        let riskWeighted: Bool?

        var advice: CaddyAdvice {
            CaddyAdvice(
                ruleId: ruleId,
                kind: CaddyAdviceKind(rawValue: kind ?? "warning") ?? .warning,
                priority: priority ?? 1,
                confidence: confidence ?? 1,
                headline: headline ?? "advice-\(ruleId)",
                detail: detail,
                vetoes: vetoes,
                riskWeighted: riskWeighted ?? false
            )
        }
    }

    private struct RunRule: Decodable {
        let id: String
        let advice: [AdviceInput]
    }
    private struct RunCase: Decodable {
        let name: String
        let riskAversion: Double
        let rules: [RunRule]
        let expected: [String]
    }
    private struct RunFx: Decodable { let cases: [RunCase] }

    private struct SummaryFx: Decodable {
        let fallLineBearingDeg: Double
        let fallLinePct: Double
        let frontHalfPct: Double
        let backHalfPct: Double
        var summary: GreenSlopeSummary {
            GreenSlopeSummary(
                fallLineBearingDeg: fallLineBearingDeg,
                fallLinePct: fallLinePct,
                frontHalfPct: frontHalfPct,
                backHalfPct: backHalfPct
            )
        }
    }

    private struct AdviceOut: Decodable {
        let ruleId: String
        let kind: String
        let priority: Double
        let confidence: Double
        let headline: String
        let detail: String?
        let anchor: XY?
    }

    private struct GsCase: Decodable {
        let name: String
        let leg: String
        let origin: XY
        let front: XY
        let center: XY
        let back: XY
        let greenSlope: SummaryFx?
        let hazards: [RingFx]
        let out: [AdviceOut]
    }
    private struct GsConstants: Decodable {
        let MIN_FALL_LINE_PCT: Double
        let FALL_LINE_ALIGN_TOLERANCE_DEG: Double
        let FRONT_CLEAN_WINDOW_M: Double
    }
    private struct GsFx: Decodable { let constants: GsConstants; let cases: [GsCase] }

    // MARK: - Per-rule fixture schema (medicine / no-doubles / short-side /
    //          specific-target / par5). Each case serializes the full context
    //          the rule reads plus runCaddy's advice for [rule].

    /// A club carrying a name — the ported rules speak club names via `clubName`.
    private struct FxClub: ClubSpec, Decodable {
        let name: String?
        let carryM: Double
        let dispersionM: Double
        var clubName: String? { name }
    }

    private struct WindFx: Decodable {
        let speedMps: Double
        let directionDeg: Double
        var wind: FeatureWind { FeatureWind(speedMps: speedMps, directionDeg: directionDeg) }
    }

    private struct HoleFx: Decodable { let par: Int; let index: Int }
    private struct RiskFx: Decodable { let riskAversion: Double }

    private struct AimBestFx: Decodable {
        let expectedStrokes: Double
        let tailStrokes: Double
    }
    private struct AimFx: Decodable {
        let bestBearingDeg: Double
        let best: AimBestFx
        let breakdown: [String: Double]
        /// Rebuild the minimal AimResult the rules read (score unused → mean).
        var aim: AimResult {
            var b: [Lie: Double] = [:]
            for (k, v) in breakdown { if let lie = Lie(rawValue: k) { b[lie] = v } }
            let candidate = AimCandidate(
                bearingDeg: bestBearingDeg,
                expectedStrokes: best.expectedStrokes,
                tailStrokes: best.tailStrokes,
                score: best.expectedStrokes,
                breakdown: b
            )
            return AimResult(
                bestBearingDeg: bestBearingDeg,
                best: candidate,
                perCandidate: [candidate],
                breakdown: b
            )
        }
    }

    private struct TargetFx: Decodable {
        let greenPoly: RingFx
        let center: XY
        let front: XY
        let back: XY
    }

    private struct CtxFx: Decodable {
        let leg: String
        let origin: XY
        let target: TargetFx
        let clubs: [FxClub]
        let wind: WindFx?
        let hole: HoleFx
        let risk: RiskFx
        let aim: AimFx?
        let hazards: [RingFx]

        var context: CaddyContext<FxClub> {
            CaddyContext<FxClub>(
                leg: CaddyLeg(rawValue: leg) ?? .approach,
                origin: StrategyPoint(x: origin.x, y: origin.y),
                target: CaddyGreenTarget(
                    greenPoly: target.greenPoly.ring,
                    center: target.center.vec,
                    front: target.front.vec,
                    back: target.back.vec
                ),
                aim: aim?.aim,
                hazards: hazards.map(\.ring),
                clubs: clubs,
                wind: wind?.wind,
                hole: CaddyHole(par: hole.par, index: hole.index),
                risk: RiskProfile(riskAversion: risk.riskAversion)
            )
        }
    }

    private struct RuleCaseFx: Decodable {
        let name: String
        let ctx: CtxFx
        let out: [AdviceOut]
    }
    private struct RuleFx: Decodable { let cases: [RuleCaseFx] }

    private struct CaddyFx: Decodable {
        let run: RunFx
        let greenSlope: GsFx
        let medicine: RuleFx
        let noDoubles: RuleFx
        let shortSide: RuleFx
        let specificTarget: RuleFx
        let par5: RuleFx
    }
    private struct Goldens: Decodable { let caddy: CaddyFx }

    private func loadCaddy() throws -> CaddyFx {
        try JSONDecoder().decode(Goldens.self, from: FixtureLoader.data("strategy-goldens.json")).caddy
    }

    // MARK: - runCaddy

    func testRunCaddyMatchesTS() throws {
        for c in try loadCaddy().run.cases {
            let rules: [CaddyRule<DummyClub>] = c.rules.map { r in
                let advice = r.advice.map(\.advice)
                return CaddyRule<DummyClub>(id: r.id, appliesTo: { _ in true }, evaluate: { _ in advice })
            }
            let ctx = Self.runContext(riskAversion: c.riskAversion)
            let out = runCaddy(ctx, rules)
            XCTAssertEqual(out.map(\.ruleId), c.expected, "runCaddy: \(c.name)")
        }
    }

    private static func runContext(riskAversion: Double) -> CaddyContext<DummyClub> {
        CaddyContext<DummyClub>(
            leg: .approach,
            origin: StrategyPoint(x: 0, y: 0),
            target: CaddyGreenTarget(
                greenPoly: FlatRing(points: [], kind: "green"),
                center: Vec2(x: 0, y: 100),
                front: Vec2(x: 0, y: 95),
                back: Vec2(x: 0, y: 105)
            ),
            hole: CaddyHole(par: 4, index: 1),
            risk: RiskProfile(riskAversion: riskAversion)
        )
    }

    // MARK: - green-slope-half constants

    func testGreenSlopeConstantsMatchTS() throws {
        let k = try loadCaddy().greenSlope.constants
        XCTAssertEqual(MIN_FALL_LINE_PCT, k.MIN_FALL_LINE_PCT, accuracy: acc)
        XCTAssertEqual(FALL_LINE_ALIGN_TOLERANCE_DEG, k.FALL_LINE_ALIGN_TOLERANCE_DEG, accuracy: acc)
        XCTAssertEqual(FRONT_CLEAN_WINDOW_M, k.FRONT_CLEAN_WINDOW_M, accuracy: acc)
    }

    // MARK: - green-slope-half rule

    func testGreenSlopeHalfMatchesTS() throws {
        for c in try loadCaddy().greenSlope.cases {
            let ctx = CaddyContext<DummyClub>(
                leg: CaddyLeg(rawValue: c.leg) ?? .approach,
                origin: StrategyPoint(x: c.origin.x, y: c.origin.y),
                target: CaddyGreenTarget(
                    greenPoly: FlatRing(points: [], kind: "green"),
                    center: c.center.vec,
                    front: c.front.vec,
                    back: c.back.vec
                ),
                greenSlope: c.greenSlope?.summary,
                hazards: c.hazards.map(\.ring),
                hole: CaddyHole(par: 4, index: 1),
                risk: RiskProfile(riskAversion: 0)
            )
            let out = runCaddy(ctx, [greenSlopeHalfRule()])
            assertAdvice(out, c.out, tag: "green-slope: \(c.name)")
        }
    }

    // MARK: - The five aim/geometry rules

    func testTakeYourMedicineMatchesTS() throws {
        try assertRule(loadCaddy().medicine, takeYourMedicineRule(), label: "take-your-medicine")
    }

    func testNoDoublesMatchesTS() throws {
        try assertRule(loadCaddy().noDoubles, noDoublesRule(), label: "no-doubles")
    }

    func testShortSideGuardMatchesTS() throws {
        try assertRule(loadCaddy().shortSide, shortSideGuardRule(), label: "short-side-guard")
    }

    func testSpecificTargetMatchesTS() throws {
        try assertRule(loadCaddy().specificTarget, specificTargetRule(), label: "specific-target")
    }

    func testPar5AttackMatchesTS() throws {
        try assertRule(loadCaddy().par5, par5AttackRule(), label: "par5-attack")
    }

    // MARK: - Shared assertions

    /// Replay every case of a per-rule fixture: rebuild the context, run the
    /// single rule through `runCaddy`, and assert per-field parity.
    private func assertRule(_ fx: RuleFx, _ rule: CaddyRule<FxClub>, label: String) {
        for c in fx.cases {
            let out = runCaddy(c.ctx.context, [rule])
            assertAdvice(out, c.out, tag: "\(label): \(c.name)")
        }
    }

    private func assertAdvice(_ out: [CaddyAdvice], _ expected: [AdviceOut], tag: String) {
        XCTAssertEqual(out.count, expected.count, "\(tag): advice count")
        guard out.count == expected.count else { return }
        for (a, e) in zip(out, expected) {
            XCTAssertEqual(a.ruleId, e.ruleId, "\(tag) ruleId")
            XCTAssertEqual(a.kind.rawValue, e.kind, "\(tag) kind")
            XCTAssertEqual(a.priority, e.priority, accuracy: acc, "\(tag) priority")
            XCTAssertEqual(a.confidence, e.confidence, accuracy: acc, "\(tag) confidence")
            XCTAssertEqual(a.headline, e.headline, "\(tag) headline")
            XCTAssertEqual(a.detail, e.detail, "\(tag) detail")
            XCTAssertEqual(a.anchor, e.anchor?.vec, "\(tag) anchor")
        }
    }
}
