import XCTest
@testable import GolfMap

/// TS ↔ Swift parity for the putting core: replays every golden case from
/// `putting-goldens.json` (generated by
/// `shared/strategy/putting/generate-swift-fixtures.ts` — regenerate with
/// `bun generate-swift-fixtures.ts` from that directory) and asserts the
/// Swift mirror reproduces the TS outputs.
///
/// Tolerances: closed-form values must match to 1e-9 (they are expected to
/// be bit-identical — Bun/JSC and Swift share Apple's libm); integrator
/// outputs to 1e-6 relative. Strings (verbal reads, enums) match exactly.
final class PuttingGoldenParityTests: XCTestCase {

    // MARK: - Fixture schema

    /// A JSON number, or the string "Infinity"/"-Infinity" (JSON has no ∞).
    private struct DoubleOrInfinity: Decodable {
        let value: Double

        init(from decoder: Decoder) throws {
            let c = try decoder.singleValueContainer()
            if let d = try? c.decode(Double.self) {
                value = d
            } else {
                let s = try c.decode(String.self)
                switch s {
                case "Infinity": value = .infinity
                case "-Infinity": value = -.infinity
                default:
                    throw DecodingError.dataCorruptedError(
                        in: c, debugDescription: "Unexpected non-finite encoding: \(s)"
                    )
                }
            }
        }
    }

    private struct P: Decodable {
        let x: Double
        let y: Double
        var vec: Vec2 { Vec2(x: x, y: y) }
    }

    private struct ArgOut: Decodable {
        let arg: Double
        let out: Double
    }

    private struct AimRefCase: Decodable {
        let paces: Double
        let slopePct: Double
        let out: Double
    }

    private struct AimCase: Decodable {
        let paces: Double
        let slopePct: Double
        let stimpFt: Double
        let out: Double
    }

    private struct BreakMultCase: Decodable {
        let mu: Double
        let gradeFraction: Double
        let out: DoubleOrInfinity
    }

    private struct PlaysLikeCase: Decodable {
        let distanceM: Double
        let gradeDeltaM: Double
        let mu: Double
        let playsLikeMeters: Double
        let canStop: Bool
    }

    private struct Scalars: Decodable {
        let stimpToFriction: [ArgOut]
        let metersToPaces: [ArgOut]
        let inchesToMeters: [ArgOut]
        let stimpBreakScale: [ArgOut]
        let tourReadAimInchesAtReference: [AimRefCase]
        let tourReadAimInches: [AimCase]
        let breakMultiplier: [BreakMultCase]
        let playsLikeLength: [PlaysLikeCase]
        let captureRadiusM: [ArgOut]
    }

    private struct TourReadInput: Decodable {
        let distanceM: Double
        let gradeDeltaM: Double
        let slopePct: Double
        let stimpFt: Double
        let breakToRight: Bool
    }

    private struct TourReadOut: Decodable {
        let aimOffsetMeters: Double
        let aimInches: Double
        let aimSide: String
        let playsLikeMeters: Double
        let breakMultiplier: DoubleOrInfinity
        let canStop: Bool
    }

    private struct VerbalOut: Decodable {
        let aim: String
        let pace: String
        let combined: String
    }

    private struct TourReadVerbals: Decodable {
        let metric: VerbalOut
        let imperial: VerbalOut
    }

    private struct TourReadCase: Decodable {
        let name: String
        let input: TourReadInput
        let read: TourReadOut
        let verbal: TourReadVerbals
    }

    private struct PlaneSpec: Decodable {
        let slopePct: Double
        let fallLineBearingDeg: Double
        let originHeight: Double?
        let confidence: Double?
    }

    private struct OptionsFx: Decodable {
        let sweepDeg: Double?
        let bearingCandidates: Int?
        let speedCandidates: Int?
        let refinePasses: Int?

        var options: PuttReadOptions {
            PuttReadOptions(
                sweepDeg: sweepDeg,
                bearingCandidates: bearingCandidates,
                speedCandidates: speedCandidates,
                refinePasses: refinePasses
            )
        }
    }

    private struct ReadFx: Decodable {
        let availability: String
        let aimBearingDeg: Double
        let aimOffsetM: Double
        let initialSpeedMps: Double
        let playsLikeM: Double
        let holedProb: Double
        let canStop: Bool
        let holed: Bool
        let pathLength: Int
        let path: [P]
        let stopPoint: P?
        let restBeyondHoleM: Double?
        let minConfidence: Double
    }

    private struct PlaneCase: Decodable {
        let name: String
        let surface: PlaneSpec
        let ball: P
        let hole: P
        let stimpFt: Double
        let options: OptionsFx?
        let read: ReadFx
    }

    private struct DemGridFx: Decodable {
        let originE: Double
        let originN: Double
        let resolution: Double
        let width: Int
        let height: Int
        let heights: [Double?]
        let insideMask: [Int]

        /// TS DemGrid → iOS SampleGrid boundary mapping (see DemSurface.swift
        /// header): null heights → NaN, insideMask 1/0 → Bool.
        var sampleGrid: SampleGrid {
            SampleGrid(
                spec: AnalysisGridSpec(
                    originE: originE, originN: originN, resolution: resolution,
                    width: width, height: height
                ),
                heights: heights.map { $0 ?? .nan },
                insideMask: insideMask.map { $0 == 1 }
            )
        }
    }

    private struct SampleFx: Decodable {
        let height: Double
        let gradX: Double
        let gradY: Double
        let confidence: Double
    }

    private struct DemSampleCase: Decodable {
        let name: String
        let p: P
        let sample: SampleFx?
    }

    private struct DemReadCase: Decodable {
        let name: String
        let ball: P
        let hole: P
        let stimpFt: Double
        let read: ReadFx
    }

    private struct DemFx: Decodable {
        let grid: DemGridFx
        let samples: [DemSampleCase]
        let reads: [DemReadCase]
    }

    private struct Goldens: Decodable {
        let constants: [String: Double]
        let scalars: Scalars
        let tourReadCases: [TourReadCase]
        let puttPlaneCases: [PlaneCase]
        let dem: DemFx
    }

    private func loadGoldens() throws -> Goldens {
        try JSONDecoder().decode(Goldens.self, from: FixtureLoader.data("putting-goldens.json"))
    }

    // MARK: - Tolerances

    /// Closed-form parity: expected bit-identical; 1e-9 absolute headroom.
    private let closedFormAccuracy = 1e-9

    /// Integrator parity: 1e-6 relative (floored at 1e-9 absolute near zero).
    private func assertRel(
        _ actual: Double, _ expected: Double, _ label: String,
        file: StaticString = #filePath, line: UInt = #line
    ) {
        let accuracy = max(1e-9, 1e-6 * abs(expected))
        XCTAssertEqual(actual, expected, accuracy: accuracy, label, file: file, line: line)
    }

    private func assertRead(
        _ actual: PuttRead, _ expected: ReadFx, _ name: String,
        file: StaticString = #filePath, line: UInt = #line
    ) {
        XCTAssertEqual(actual.availability.rawValue, expected.availability,
                       "\(name): availability", file: file, line: line)
        assertRel(actual.aimBearingDeg, expected.aimBearingDeg, "\(name): aimBearingDeg",
                  file: file, line: line)
        assertRel(actual.aimOffsetM, expected.aimOffsetM, "\(name): aimOffsetM",
                  file: file, line: line)
        assertRel(actual.initialSpeedMps, expected.initialSpeedMps, "\(name): initialSpeedMps",
                  file: file, line: line)
        assertRel(actual.playsLikeM, expected.playsLikeM, "\(name): playsLikeM",
                  file: file, line: line)
        assertRel(actual.holedProb, expected.holedProb, "\(name): holedProb",
                  file: file, line: line)
        XCTAssertEqual(actual.canStop, expected.canStop, "\(name): canStop",
                       file: file, line: line)
        XCTAssertEqual(actual.holed, expected.holed, "\(name): holed", file: file, line: line)
        assertRel(actual.minConfidence, expected.minConfidence, "\(name): minConfidence",
                  file: file, line: line)

        XCTAssertEqual(actual.path.count, expected.pathLength, "\(name): path length",
                       file: file, line: line)
        if actual.path.count == expected.path.count {
            for (i, (a, e)) in zip(actual.path, expected.path).enumerated() {
                // Positions are meters (possibly large EPSG:3006 values);
                // with shared libm these are bit-identical — 1e-6 m headroom.
                XCTAssertEqual(a.x, e.x, accuracy: 1e-6, "\(name): path[\(i)].x",
                               file: file, line: line)
                XCTAssertEqual(a.y, e.y, accuracy: 1e-6, "\(name): path[\(i)].y",
                               file: file, line: line)
            }
        }

        XCTAssertEqual(actual.stopPoint == nil, expected.stopPoint == nil,
                       "\(name): stopPoint nil-ness", file: file, line: line)
        if let a = actual.stopPoint, let e = expected.stopPoint {
            XCTAssertEqual(a.x, e.x, accuracy: 1e-6, "\(name): stopPoint.x", file: file, line: line)
            XCTAssertEqual(a.y, e.y, accuracy: 1e-6, "\(name): stopPoint.y", file: file, line: line)
        }

        XCTAssertEqual(actual.restBeyondHoleM == nil, expected.restBeyondHoleM == nil,
                       "\(name): restBeyondHoleM nil-ness", file: file, line: line)
        if let a = actual.restBeyondHoleM, let e = expected.restBeyondHoleM {
            assertRel(a, e, "\(name): restBeyondHoleM", file: file, line: line)
        }
    }

    // MARK: - Constants

    func testConstantsMatchTS() throws {
        let g = try loadGoldens()
        let swift: [String: Double] = [
            "STIMP_RELEASE_V0_MPS": STIMP_RELEASE_V0_MPS,
            "GRAVITY_MPS2": GRAVITY_MPS2,
            "FEET_TO_METERS": FEET_TO_METERS,
            "FRICTION_CONSTANT": FRICTION_CONSTANT,
            "PACE_METERS": PACE_METERS,
            "INCHES_TO_METERS": INCHES_TO_METERS,
            "TOUR_READ_REFERENCE_STIMP_FT": TOUR_READ_REFERENCE_STIMP_FT,
            "STIMP_BREAK_SCALE_PER_FT": STIMP_BREAK_SCALE_PER_FT,
            "HOLE_RADIUS_M": HOLE_RADIUS_M,
            "LIP_OUT_SPEED_MPS": LIP_OUT_SPEED_MPS,
            "DEM_DEFAULT_CONFIDENCE": DEM_DEFAULT_CONFIDENCE,
        ]
        XCTAssertEqual(Set(swift.keys), Set(g.constants.keys), "constant sets differ")
        for (name, expected) in g.constants {
            XCTAssertEqual(swift[name]!, expected, accuracy: closedFormAccuracy, name)
        }
    }

    // MARK: - Closed-form scalars

    func testScalarFunctionsMatchTS() throws {
        let s = try loadGoldens().scalars
        for c in s.stimpToFriction {
            XCTAssertEqual(stimpToFriction(c.arg), c.out, accuracy: closedFormAccuracy,
                           "stimpToFriction(\(c.arg))")
        }
        for c in s.metersToPaces {
            XCTAssertEqual(metersToPaces(c.arg), c.out, accuracy: closedFormAccuracy,
                           "metersToPaces(\(c.arg))")
        }
        for c in s.inchesToMeters {
            XCTAssertEqual(inchesToMeters(c.arg), c.out, accuracy: closedFormAccuracy,
                           "inchesToMeters(\(c.arg))")
        }
        for c in s.stimpBreakScale {
            XCTAssertEqual(stimpBreakScale(c.arg), c.out, accuracy: closedFormAccuracy,
                           "stimpBreakScale(\(c.arg))")
        }
        for c in s.tourReadAimInchesAtReference {
            XCTAssertEqual(tourReadAimInchesAtReference(c.paces, c.slopePct), c.out,
                           accuracy: closedFormAccuracy,
                           "tourReadAimInchesAtReference(\(c.paces), \(c.slopePct))")
        }
        for c in s.tourReadAimInches {
            XCTAssertEqual(tourReadAimInches(c.paces, c.slopePct, c.stimpFt), c.out,
                           accuracy: closedFormAccuracy,
                           "tourReadAimInches(\(c.paces), \(c.slopePct), \(c.stimpFt))")
        }
        for c in s.breakMultiplier {
            let actual = breakMultiplier(mu: c.mu, gradeFraction: c.gradeFraction)
            if c.out.value.isInfinite {
                XCTAssertEqual(actual, c.out.value,
                               "breakMultiplier(\(c.mu), \(c.gradeFraction)) should diverge")
            } else {
                XCTAssertEqual(actual, c.out.value, accuracy: closedFormAccuracy,
                               "breakMultiplier(\(c.mu), \(c.gradeFraction))")
            }
        }
        for c in s.playsLikeLength {
            let r = playsLikeLength(distanceM: c.distanceM, gradeDeltaM: c.gradeDeltaM, mu: c.mu)
            XCTAssertEqual(r.playsLikeMeters, c.playsLikeMeters, accuracy: closedFormAccuracy,
                           "playsLikeLength(\(c.distanceM), \(c.gradeDeltaM))")
            XCTAssertEqual(r.canStop, c.canStop, "playsLikeLength canStop(\(c.gradeDeltaM))")
        }
        for c in s.captureRadiusM {
            XCTAssertEqual(captureRadiusM(c.arg), c.out, accuracy: closedFormAccuracy,
                           "captureRadiusM(\(c.arg))")
        }
    }

    // MARK: - Assembled tourRead + verbal formatter

    func testTourReadCasesMatchTS() throws {
        for c in try loadGoldens().tourReadCases {
            let r = tourRead(
                distanceM: c.input.distanceM,
                gradeDeltaM: c.input.gradeDeltaM,
                slopePct: c.input.slopePct,
                stimpFt: c.input.stimpFt,
                breakToRight: c.input.breakToRight
            )
            XCTAssertEqual(r.aimOffsetMeters, c.read.aimOffsetMeters,
                           accuracy: closedFormAccuracy, "\(c.name): aimOffsetMeters")
            XCTAssertEqual(r.aimInches, c.read.aimInches,
                           accuracy: closedFormAccuracy, "\(c.name): aimInches")
            XCTAssertEqual(r.aimSide.rawValue, c.read.aimSide, "\(c.name): aimSide")
            XCTAssertEqual(r.playsLikeMeters, c.read.playsLikeMeters,
                           accuracy: closedFormAccuracy, "\(c.name): playsLikeMeters")
            if c.read.breakMultiplier.value.isInfinite {
                XCTAssertEqual(r.breakMultiplier, c.read.breakMultiplier.value,
                               "\(c.name): breakMultiplier should diverge")
            } else {
                XCTAssertEqual(r.breakMultiplier, c.read.breakMultiplier.value,
                               accuracy: closedFormAccuracy, "\(c.name): breakMultiplier")
            }
            XCTAssertEqual(r.canStop, c.read.canStop, "\(c.name): canStop")

            let metric = formatTourRead(r, units: .metric)
            XCTAssertEqual(metric.aim, c.verbal.metric.aim, "\(c.name): metric aim")
            XCTAssertEqual(metric.pace, c.verbal.metric.pace, "\(c.name): metric pace")
            XCTAssertEqual(metric.combined, c.verbal.metric.combined, "\(c.name): metric combined")
            let imperial = formatTourRead(r, units: .imperial)
            XCTAssertEqual(imperial.aim, c.verbal.imperial.aim, "\(c.name): imperial aim")
            XCTAssertEqual(imperial.pace, c.verbal.imperial.pace, "\(c.name): imperial pace")
            XCTAssertEqual(imperial.combined, c.verbal.imperial.combined,
                           "\(c.name): imperial combined")
        }
    }

    // MARK: - Integrator on PlaneSurface

    func testPlanePuttReadsMatchTS() throws {
        for c in try loadGoldens().puttPlaneCases {
            let surface = PlaneSurface(
                slopePct: c.surface.slopePct,
                fallLineBearingDeg: c.surface.fallLineBearingDeg,
                originHeight: c.surface.originHeight ?? 0,
                confidence: c.surface.confidence ?? 1
            )
            let read = readPutt(
                surface: surface, ball: c.ball.vec, hole: c.hole.vec,
                stimpFt: c.stimpFt, options: c.options?.options
            )
            assertRead(read, c.read, c.name)
        }
    }

    // MARK: - DemSurface samples + integrator on the DEM grid

    func testDemSamplesMatchTS() throws {
        let dem = try loadGoldens().dem
        let surface = DemSurface(grid: dem.grid.sampleGrid)
        for c in dem.samples {
            let s = surface.sampleAt(c.p.vec)
            if let expected = c.sample {
                let sample = try XCTUnwrap(s, "\(c.name): expected a sample, got nil")
                XCTAssertEqual(sample.height, expected.height, accuracy: closedFormAccuracy,
                               "\(c.name): height")
                XCTAssertEqual(sample.gradX, expected.gradX, accuracy: closedFormAccuracy,
                               "\(c.name): gradX")
                XCTAssertEqual(sample.gradY, expected.gradY, accuracy: closedFormAccuracy,
                               "\(c.name): gradY")
                XCTAssertEqual(sample.confidence, expected.confidence,
                               accuracy: closedFormAccuracy, "\(c.name): confidence")
            } else {
                XCTAssertNil(s, "\(c.name): expected nil (off coverage)")
            }
        }
    }

    func testDemPuttReadsMatchTS() throws {
        let dem = try loadGoldens().dem
        let surface = DemSurface(grid: dem.grid.sampleGrid)
        for c in dem.reads {
            let read = readPutt(
                surface: surface, ball: c.ball.vec, hole: c.hole.vec, stimpFt: c.stimpFt
            )
            assertRead(read, c.read, c.name)
        }
    }
}
