import XCTest
@testable import GolfMap

/// TS ↔ Swift parity for the four shot-visualization strategy modules
/// (Ellipse, Lie, ExpectedStrokes, Aim): replays every golden case from
/// `strategy-goldens.json` (generated by `shared/strategy/generate-swift-fixtures.ts`
/// — regenerate with `bun generate-swift-fixtures.ts` from that directory) and
/// asserts the Swift mirror reproduces the TS outputs.
///
/// Tolerance 1e-9 absolute (Bun/JSC and Swift share Apple's libm). Strings
/// match exactly. Determinism (aim sampling) is expected bit-comparable.
final class StrategyShotVizParityTests: XCTestCase {

    private let acc = 1e-9

    // MARK: - Shared fixture schema

    private struct FxClub: Decodable, ClubSpec {
        let name: String
        let carryM: Double
        let dispersionM: Double
    }

    private struct XY: Decodable {
        let x: Double
        let y: Double
        var vec: Vec2 { Vec2(x: x, y: y) }
    }

    private struct RingFx: Decodable {
        let kind: String
        let points: [XY]
        var ring: FlatRing { FlatRing(points: points.map(\.vec), kind: kind) }
    }

    // MARK: - Ellipse section

    private struct EllipseCase: Decodable {
        let name: String
        let origin: XY
        let bearingDeg: Double
        let club: FxClub
        let windSpeedMps: Double?
        let windDirectionDeg: Double?
        let groundSlope: Double?
        let samples: Int?
        let center: XY
        let driftM: Double
        let semiLengthM: Double
        let semiLateralM: Double
        let resultBearingDeg: Double
        let polygon: [XY]
    }
    private struct EllipseFx: Decodable { let cases: [EllipseCase] }

    private struct RingRadiiCase: Decodable { let par: Int; let radii: [Double] }
    private struct RingConstants: Decodable {
        let GREEN_RING_RADII_M: [Double]
        let GREEN_RING_PAR5_EXTRA_M: Double
        let TEE_RING_RADII_M: [Double]
    }
    private struct RingPolygonCase: Decodable {
        let name: String
        let center: XY
        let radiusM: Double
        let samples: Int?
        let polygon: [XY]
    }
    private struct RingsFx: Decodable {
        let greenRingRadiiM: [RingRadiiCase]
        let constants: RingConstants
        let ringPolygon: [RingPolygonCase]
    }

    // MARK: - Lie section

    private struct LieCase: Decodable { let featureType: String; let lie: String }
    private struct LieFx: Decodable { let lieFromFeatureType: [LieCase] }

    // MARK: - ExpectedStrokes section

    private struct ShotCase: Decodable { let distanceM: Double; let lie: String; let out: Double }
    private struct SGCase: Decodable {
        let fromM: Double
        let fromLie: String
        let toM: Double
        let toLie: String
        let out: Double
    }
    private struct ExpectedStrokesFx: Decodable {
        let HOLED_DISTANCE_M: Double
        let shotsToHoleOut: [ShotCase]
        let strokesGained: [SGCase]
    }

    // MARK: - Aim section

    private struct SweepCase: Decodable { let name: String; let club: FxClub; let out: Double }
    private struct NormalPairsCase: Decodable { let count: Int; let pairs: [[Double]] }
    private struct CandidateFx: Decodable {
        let bearingDeg: Double
        let expectedStrokes: Double
        let tailStrokes: Double
        let score: Double
        let breakdown: [String: Double]
    }
    private struct AimCaseFx: Decodable {
        let name: String
        let origin: XY
        let club: FxClub
        let targetBearingDeg: Double
        let greenCenter: XY
        let surfaces: [RingFx]
        let windSpeedMps: Double?
        let windDirectionDeg: Double?
        let groundSlope: Double?
        let sweepDeg: Double?
        let candidates: Int?
        let samples: Int?
        let sigmaScale: Double?
        let riskAversion: Double?
        let fallbackLie: String?
        let bestBearingDeg: Double
        let breakdown: [String: Double]
        let perCandidate: [CandidateFx]
    }
    private struct AimFx: Decodable {
        let defaultSweepDeg: [SweepCase]
        let standardNormalPairs: [NormalPairsCase]
        let cases: [AimCaseFx]
    }

    private struct Goldens: Decodable {
        let ellipse: EllipseFx
        let rings: RingsFx
        let lie: LieFx
        let expectedStrokes: ExpectedStrokesFx
        let aim: AimFx
    }

    private func loadGoldens() throws -> Goldens {
        try JSONDecoder().decode(Goldens.self, from: FixtureLoader.data("strategy-goldens.json"))
    }

    // MARK: - Ellipse

    func testDispersionEllipseMatchesTS() throws {
        for c in try loadGoldens().ellipse.cases {
            let e = dispersionEllipse(DispersionEllipseOptions(
                origin: c.origin.vec,
                bearingDeg: c.bearingDeg,
                club: c.club,
                windSpeedMps: c.windSpeedMps,
                windDirectionDeg: c.windDirectionDeg,
                groundSlope: c.groundSlope,
                samples: c.samples
            ))
            let tag = "ellipse[\(c.name)]"
            XCTAssertEqual(e.center.x, c.center.x, accuracy: acc, "\(tag) center.x")
            XCTAssertEqual(e.center.y, c.center.y, accuracy: acc, "\(tag) center.y")
            XCTAssertEqual(e.driftM, c.driftM, accuracy: acc, "\(tag) driftM")
            XCTAssertEqual(e.semiLengthM, c.semiLengthM, accuracy: acc, "\(tag) semiLengthM")
            XCTAssertEqual(e.semiLateralM, c.semiLateralM, accuracy: acc, "\(tag) semiLateralM")
            XCTAssertEqual(e.bearingDeg, c.resultBearingDeg, accuracy: acc, "\(tag) bearingDeg")
            XCTAssertEqual(e.polygon.count, c.polygon.count, "\(tag) polygon count")
            guard e.polygon.count == c.polygon.count else { continue }
            for (i, (a, ex)) in zip(e.polygon, c.polygon).enumerated() {
                XCTAssertEqual(a.x, ex.x, accuracy: acc, "\(tag) polygon[\(i)].x")
                XCTAssertEqual(a.y, ex.y, accuracy: acc, "\(tag) polygon[\(i)].y")
            }
        }
    }

    func testDistanceRingsMatchTS() throws {
        let r = try loadGoldens().rings
        XCTAssertEqual(GREEN_RING_RADII_M, r.constants.GREEN_RING_RADII_M, "GREEN_RING_RADII_M")
        XCTAssertEqual(GREEN_RING_PAR5_EXTRA_M, r.constants.GREEN_RING_PAR5_EXTRA_M, accuracy: acc, "GREEN_RING_PAR5_EXTRA_M")
        XCTAssertEqual(TEE_RING_RADII_M, r.constants.TEE_RING_RADII_M, "TEE_RING_RADII_M")

        for c in r.greenRingRadiiM {
            XCTAssertEqual(greenRingRadiiM(c.par), c.radii, "greenRingRadiiM(\(c.par))")
        }

        for c in r.ringPolygon {
            let poly = c.samples == nil
                ? ringPolygon(c.center.vec, c.radiusM)
                : ringPolygon(c.center.vec, c.radiusM, samples: c.samples!)
            let tag = "ringPolygon[\(c.name)]"
            XCTAssertEqual(poly.count, c.polygon.count, "\(tag) count")
            guard poly.count == c.polygon.count else { continue }
            for (i, (a, ex)) in zip(poly, c.polygon).enumerated() {
                XCTAssertEqual(a.x, ex.x, accuracy: acc, "\(tag) [\(i)].x")
                XCTAssertEqual(a.y, ex.y, accuracy: acc, "\(tag) [\(i)].y")
            }
        }
    }

    // MARK: - Lie

    func testLieFromFeatureTypeMatchesTS() throws {
        for c in try loadGoldens().lie.lieFromFeatureType {
            XCTAssertEqual(lieFromFeatureType(c.featureType).rawValue, c.lie,
                           "lieFromFeatureType(\(c.featureType))")
        }
    }

    // MARK: - ExpectedStrokes

    func testExpectedStrokesMatchesTS() throws {
        let es = try loadGoldens().expectedStrokes
        XCTAssertEqual(HOLED_DISTANCE_M, es.HOLED_DISTANCE_M, accuracy: acc, "HOLED_DISTANCE_M")
        for c in es.shotsToHoleOut {
            let lie = Lie(rawValue: c.lie)!
            XCTAssertEqual(shotsToHoleOut(c.distanceM, lie), c.out, accuracy: acc,
                           "shotsToHoleOut(\(c.distanceM), \(c.lie))")
        }
        for c in es.strokesGained {
            let out = strokesGained(c.fromM, Lie(rawValue: c.fromLie)!, c.toM, Lie(rawValue: c.toLie)!)
            XCTAssertEqual(out, c.out, accuracy: acc,
                           "strokesGained(\(c.fromM),\(c.fromLie) → \(c.toM),\(c.toLie))")
        }
    }

    // MARK: - Aim

    func testDefaultSweepDegAndNormalPairsMatchTS() throws {
        let a = try loadGoldens().aim
        for c in a.defaultSweepDeg {
            XCTAssertEqual(defaultSweepDeg(c.club), c.out, accuracy: acc, "defaultSweepDeg(\(c.name))")
        }
        for c in a.standardNormalPairs {
            let pairs = standardNormalPairs(c.count)
            XCTAssertEqual(pairs.count, c.pairs.count, "standardNormalPairs(\(c.count)) count")
            guard pairs.count == c.pairs.count else { continue }
            for (i, (p, ex)) in zip(pairs, c.pairs).enumerated() {
                XCTAssertEqual(p.0, ex[0], accuracy: acc, "standardNormalPairs(\(c.count))[\(i)].0")
                XCTAssertEqual(p.1, ex[1], accuracy: acc, "standardNormalPairs(\(c.count))[\(i)].1")
            }
        }
    }

    func testOptimizeAimMatchesTS() throws {
        for c in try loadGoldens().aim.cases {
            let result = optimizeAim(AimOptions(
                origin: c.origin.vec,
                club: c.club,
                targetBearingDeg: c.targetBearingDeg,
                surfaces: c.surfaces.map(\.ring),
                greenCenter: c.greenCenter.vec,
                windSpeedMps: c.windSpeedMps,
                windDirectionDeg: c.windDirectionDeg,
                groundSlope: c.groundSlope,
                sweepDeg: c.sweepDeg,
                candidates: c.candidates,
                samples: c.samples,
                sigmaScale: c.sigmaScale,
                riskAversion: c.riskAversion,
                fallbackLie: c.fallbackLie.flatMap { Lie(rawValue: $0) }
            ))
            let tag = "aim[\(c.name)]"
            XCTAssertEqual(result.bestBearingDeg, c.bestBearingDeg, accuracy: acc, "\(tag) bestBearingDeg")
            assertBreakdown(result.breakdown, c.breakdown, "\(tag) breakdown")

            XCTAssertEqual(result.perCandidate.count, c.perCandidate.count, "\(tag) perCandidate count")
            guard result.perCandidate.count == c.perCandidate.count else { continue }
            for (i, (a, e)) in zip(result.perCandidate, c.perCandidate).enumerated() {
                let ct = "\(tag) cand[\(i)]"
                XCTAssertEqual(a.bearingDeg, e.bearingDeg, accuracy: acc, "\(ct) bearingDeg")
                XCTAssertEqual(a.expectedStrokes, e.expectedStrokes, accuracy: acc, "\(ct) expectedStrokes")
                XCTAssertEqual(a.tailStrokes, e.tailStrokes, accuracy: acc, "\(ct) tailStrokes")
                XCTAssertEqual(a.score, e.score, accuracy: acc, "\(ct) score")
                assertBreakdown(a.breakdown, e.breakdown, "\(ct) breakdown")
            }
        }
    }

    private func assertBreakdown(_ actual: [Lie: Double], _ expected: [String: Double], _ label: String) {
        XCTAssertEqual(actual.count, expected.count, "\(label) key count")
        for (key, ev) in expected {
            guard let lie = Lie(rawValue: key) else {
                XCTFail("\(label): unknown lie key \(key)")
                continue
            }
            guard let av = actual[lie] else {
                XCTFail("\(label): missing lie \(key)")
                continue
            }
            XCTAssertEqual(av, ev, accuracy: acc, "\(label)[\(key)]")
        }
    }
}
