import XCTest
@testable import GolfMap

/// TS ↔ Swift parity for the four ported strategy modules (Club, Wind, Carry,
/// FeatureDistances): replays every golden case from `strategy-goldens.json`
/// (generated by `shared/strategy/generate-swift-fixtures.ts` — regenerate
/// with `bun generate-swift-fixtures.ts` from that directory) and asserts the
/// Swift mirror reproduces the TS outputs.
///
/// Tolerances: closed-form values are expected bit-identical (Bun/JSC and
/// Swift share Apple's libm) — 1e-9 absolute headroom. Strings match exactly.
final class StrategyGoldenParityTests: XCTestCase {

    private let acc = 1e-9

    // MARK: - Fixture schema

    /// Concrete club for the fixtures (structurally a ClubSpec).
    private struct FxClub: Decodable, ClubSpec {
        let name: String
        let carryM: Double
        let dispersionM: Double
    }

    private struct XY: Decodable {
        let x: Double
        let y: Double
        var vec: Vec2 { Vec2(x: x, y: y) }
    }

    private struct SP: Decodable {
        let x: Double
        let y: Double
        let elevation: Double?
        var point: StrategyPoint { StrategyPoint(x: x, y: y, elevation: elevation) }
    }

    private struct RingFx: Decodable {
        let kind: String
        let points: [XY]
        var ring: FlatRing { FlatRing(points: points.map(\.vec), kind: kind) }
    }

    // Club section

    private struct ArgOut: Decodable { let arg: Double; let out: Double }
    private struct CarryBand: Decodable { let carryM: Double; let effect: Double; let out: Double }
    private struct DispBand: Decodable { let dispersionM: Double; let effect: Double; let out: Double }
    private struct ClosestCase: Decodable { let distanceM: Double; let name: String? }
    private struct AdviceCase: Decodable {
        let distanceM: Double
        let front: String?
        let center: String?
        let back: String?
    }
    private struct SuggestCase: Decodable { let distanceM: Double; let name: String? }

    private struct ClubFx: Decodable {
        let lengthDispersionM: [ArgOut]
        let minCarryM: [CarryBand]
        let maxCarryM: [CarryBand]
        let minDispersionM: [DispBand]
        let maxDispersionM: [DispBand]
        let closestClub: [ClosestCase]
        let closestClubEmpty: ClosestCase
        let clubAdvice: [AdviceCase]
        let suggestClubForHole: [SuggestCase]
        let suggestClubForHoleEmpty: SuggestCase
    }

    // Layup section

    private struct LayupOptionFx: Decodable {
        let club: String
        let carryM: Double
        let remainingM: Double
        let approachClub: String?
        let reaches: Bool
    }
    private struct LongestFx: Decodable {
        let club: String
        let remainingM: Double
        let approachClub: String?
    }
    private struct LayupCase: Decodable {
        let targetM: Double
        let options: [LayupOptionFx]
        let longest: LongestFx?
    }
    private struct LayupFx: Decodable {
        let cases: [LayupCase]
        let emptyOptions: Int
        let emptyLongest: String?
    }

    // Wind section

    private struct WindComponentsCase: Decodable {
        let speedMps: Double
        let directionDeg: Double
        let shotBearingDeg: Double
        let headTailMph: Double
        let crosswindMph: Double
    }
    private struct WindEffectCase: Decodable {
        let speedMps: Double
        let directionDeg: Double
        let shotBearingDeg: Double
        let shotDistanceM: Double
        let out: Double
    }
    private struct EffectPairCase: Decodable { let carryM: Double; let effect: Double; let out: Double }
    private struct PlaysAsCase: Decodable { let distanceM: Double; let effect: Double; let out: Double }
    private struct DriftCase: Decodable { let carryM: Double; let crosswindMph: Double; let out: Double }

    private struct WindFx: Decodable {
        let windComponents: [WindComponentsCase]
        let windEffect: [WindEffectCase]
        let adjustedCarryM: [EffectPairCase]
        let playsAsM: [PlaysAsCase]
        let crosswindDriftM: [DriftCase]
    }

    // Carry section

    private struct HazardFx: Decodable { let kind: String; let frontM: Double; let carryM: Double }
    private struct CarryCase: Decodable {
        let name: String
        let origin: XY
        let bearingDeg: Double
        let rings: [RingFx]
        let hazards: [HazardFx]
    }
    private struct CarryFx: Decodable { let cases: [CarryCase] }

    // FeatureDistances section

    private struct TargetFx: Decodable {
        let kind: String
        let label: String
        let role: String?
        let at: SP?
        let ring: RingFx?
        var target: DistanceTarget {
            if kind == "point" {
                return .point(label: label, role: FeatureDistanceKind(rawValue: role!)!, at: at!.point)
            }
            return .hazard(label: label, ring: ring!.ring)
        }
    }
    private struct WindInputFx: Decodable { let speedMps: Double; let directionDeg: Double }
    private struct RowFx: Decodable {
        let kind: String
        let label: String
        let bearingDeg: Double
        let lineM: Double
        let elevationDeltaM: Double?
        let playsLikeM: Double?
        let windDeltaM: Double?
        let clubName: String?
    }
    private struct FeatureCase: Decodable {
        let name: String
        let origin: SP
        let targets: [TargetFx]
        let bearingDeg: Double
        let wind: WindInputFx?
        let hasClubs: Bool
        let rows: [RowFx]
    }
    private struct FeatureFx: Decodable { let clubs: [FxClub]; let cases: [FeatureCase] }

    private struct Constants: Decodable { let MPS_TO_MPH: Double }

    private struct Goldens: Decodable {
        let constants: Constants
        let clubs: [FxClub]
        let club: ClubFx
        let layup: LayupFx
        let wind: WindFx
        let carry: CarryFx
        let featureDistances: FeatureFx
    }

    private func loadGoldens() throws -> Goldens {
        try JSONDecoder().decode(Goldens.self, from: FixtureLoader.data("strategy-goldens.json"))
    }

    // MARK: - Constants

    func testConstantsMatchTS() throws {
        let g = try loadGoldens()
        XCTAssertEqual(MPS_TO_MPH, g.constants.MPS_TO_MPH, accuracy: acc)
    }

    // MARK: - Club

    func testClubFunctionsMatchTS() throws {
        let g = try loadGoldens()
        let clubs = g.clubs
        let c = g.club

        for x in c.lengthDispersionM {
            XCTAssertEqual(lengthDispersionM(x.arg), x.out, accuracy: acc, "lengthDispersionM(\(x.arg))")
        }
        for x in c.minCarryM {
            XCTAssertEqual(minCarryM(x.carryM, windEffect: x.effect), x.out, accuracy: acc,
                           "minCarryM(\(x.carryM), \(x.effect))")
        }
        for x in c.maxCarryM {
            XCTAssertEqual(maxCarryM(x.carryM, windEffect: x.effect), x.out, accuracy: acc,
                           "maxCarryM(\(x.carryM), \(x.effect))")
        }
        for x in c.minDispersionM {
            XCTAssertEqual(minDispersionM(x.dispersionM, windEffect: x.effect), x.out, accuracy: acc,
                           "minDispersionM(\(x.dispersionM), \(x.effect))")
        }
        for x in c.maxDispersionM {
            XCTAssertEqual(maxDispersionM(x.dispersionM, windEffect: x.effect), x.out, accuracy: acc,
                           "maxDispersionM(\(x.dispersionM), \(x.effect))")
        }
        for x in c.closestClub {
            XCTAssertEqual(closestClub(clubs, x.distanceM)?.name, x.name, "closestClub(\(x.distanceM))")
        }
        XCTAssertEqual(closestClub([FxClub](), c.closestClubEmpty.distanceM)?.name,
                       c.closestClubEmpty.name, "closestClub(empty)")
        for x in c.clubAdvice {
            let a = clubAdvice(clubs, x.distanceM)
            XCTAssertEqual(a.front?.name, x.front, "clubAdvice(\(x.distanceM)).front")
            XCTAssertEqual(a.center?.name, x.center, "clubAdvice(\(x.distanceM)).center")
            XCTAssertEqual(a.back?.name, x.back, "clubAdvice(\(x.distanceM)).back")
        }
        for x in c.suggestClubForHole {
            XCTAssertEqual(suggestClubForHole(clubs, x.distanceM)?.name, x.name,
                           "suggestClubForHole(\(x.distanceM))")
        }
        XCTAssertEqual(suggestClubForHole([FxClub](), c.suggestClubForHoleEmpty.distanceM)?.name,
                       c.suggestClubForHoleEmpty.name, "suggestClubForHole(empty)")
    }

    // MARK: - Layup

    func testLayupMatchesTS() throws {
        let g = try loadGoldens()
        let clubs = g.clubs
        for c in g.layup.cases {
            let opts = layupOptions(clubs, c.targetM)
            XCTAssertEqual(opts.count, c.options.count, "layupOptions(\(c.targetM)) count")
            for (o, x) in zip(opts, c.options) {
                XCTAssertEqual(o.club.name, x.club, "layup(\(c.targetM)) club order")
                XCTAssertEqual(o.carryM, x.carryM, accuracy: acc, "layup(\(c.targetM)) \(x.club) carryM")
                XCTAssertEqual(o.remainingM, x.remainingM, accuracy: acc, "layup(\(c.targetM)) \(x.club) remainingM")
                XCTAssertEqual(o.approachClub?.name, x.approachClub, "layup(\(c.targetM)) \(x.club) approachClub")
                XCTAssertEqual(o.reaches, x.reaches, "layup(\(c.targetM)) \(x.club) reaches")
            }
            let longest = longestLayup(clubs, c.targetM)
            XCTAssertEqual(longest?.club.name, c.longest?.club, "longestLayup(\(c.targetM)) club")
            XCTAssertEqual(longest?.approachClub?.name, c.longest?.approachClub, "longestLayup(\(c.targetM)) approach")
            if let l = longest, let x = c.longest {
                XCTAssertEqual(l.remainingM, x.remainingM, accuracy: acc, "longestLayup(\(c.targetM)) remainingM")
            }
        }
        XCTAssertEqual(layupOptions([FxClub](), 150).count, g.layup.emptyOptions, "layupOptions(empty)")
        XCTAssertNil(longestLayup([FxClub](), 150), "longestLayup(empty)")
        XCTAssertNil(g.layup.emptyLongest, "emptyLongest golden should be null")
    }

    // MARK: - Wind

    func testWindFunctionsMatchTS() throws {
        let w = try loadGoldens().wind
        for x in w.windComponents {
            let r = windComponents(x.speedMps, x.directionDeg, x.shotBearingDeg)
            XCTAssertEqual(r.headTailMph, x.headTailMph, accuracy: acc, "windComponents headTail")
            XCTAssertEqual(r.crosswindMph, x.crosswindMph, accuracy: acc, "windComponents crosswind")
        }
        for x in w.windEffect {
            XCTAssertEqual(windEffect(x.speedMps, x.directionDeg, x.shotBearingDeg, x.shotDistanceM), x.out,
                           accuracy: acc,
                           "windEffect(\(x.speedMps), \(x.directionDeg), \(x.shotBearingDeg), \(x.shotDistanceM))")
        }
        for x in w.adjustedCarryM {
            XCTAssertEqual(adjustedCarryM(x.carryM, x.effect), x.out, accuracy: acc, "adjustedCarryM")
        }
        for x in w.playsAsM {
            XCTAssertEqual(playsAsM(x.distanceM, x.effect), x.out, accuracy: acc, "playsAsM")
        }
        for x in w.crosswindDriftM {
            XCTAssertEqual(crosswindDriftM(x.carryM, x.crosswindMph), x.out, accuracy: acc, "crosswindDriftM")
        }
    }

    // MARK: - Carry

    func testHazardsAlongLineMatchTS() throws {
        for c in try loadGoldens().carry.cases {
            let hazards = hazardsAlongLine(c.origin.vec, c.bearingDeg, c.rings.map(\.ring))
            XCTAssertEqual(hazards.count, c.hazards.count, "\(c.name): hazard count")
            guard hazards.count == c.hazards.count else { continue }
            for (i, (a, e)) in zip(hazards, c.hazards).enumerated() {
                XCTAssertEqual(a.ring.kind, e.kind, "\(c.name): hazard[\(i)] kind")
                XCTAssertEqual(a.frontM, e.frontM, accuracy: acc, "\(c.name): hazard[\(i)] frontM")
                XCTAssertEqual(a.carryM, e.carryM, accuracy: acc, "\(c.name): hazard[\(i)] carryM")
            }
        }
    }

    // MARK: - FeatureDistances

    func testFeatureDistancesMatchTS() throws {
        let fx = try loadGoldens().featureDistances
        for c in fx.cases {
            let clubs = c.hasClubs ? fx.clubs : []
            let rows: [FeatureDistance<FxClub>] = featureDistances(
                origin: c.origin.point,
                targets: c.targets.map(\.target),
                bearingDeg: c.bearingDeg,
                wind: c.wind.map { FeatureWind(speedMps: $0.speedMps, directionDeg: $0.directionDeg) },
                clubs: clubs
            )
            XCTAssertEqual(rows.count, c.rows.count, "\(c.name): row count")
            guard rows.count == c.rows.count else { continue }
            for (i, (a, e)) in zip(rows, c.rows).enumerated() {
                let tag = "\(c.name): row[\(i)]"
                XCTAssertEqual(a.kind.rawValue, e.kind, "\(tag) kind")
                XCTAssertEqual(a.label, e.label, "\(tag) label")
                XCTAssertEqual(a.bearingDeg, e.bearingDeg, accuracy: acc, "\(tag) bearingDeg")
                XCTAssertEqual(a.lineM, e.lineM, accuracy: acc, "\(tag) lineM")
                assertOptional(a.elevationDeltaM, e.elevationDeltaM, "\(tag) elevationDeltaM")
                assertOptional(a.playsLikeM, e.playsLikeM, "\(tag) playsLikeM")
                assertOptional(a.windDeltaM, e.windDeltaM, "\(tag) windDeltaM")
                XCTAssertEqual(a.club?.name, e.clubName, "\(tag) clubName")
            }
        }
    }

    private func assertOptional(_ actual: Double?, _ expected: Double?, _ label: String) {
        XCTAssertEqual(actual == nil, expected == nil, "\(label): nil-ness")
        if let a = actual, let e = expected {
            XCTAssertEqual(a, e, accuracy: acc, label)
        }
    }
}
