import MapLibre
import SwiftUI

/// SwiftUI map view for one downloaded course bundle: offline ortho raster
/// basemap + course feature polygons (web editor palette) + dynamic overlays
/// (distance line, target markers, custom GPS dot).
///
/// Self-contained: everything comes in through the initializer — no app
/// environment. The style is generated by `MapStyleBuilder`, written to a
/// temp file, and loaded via `MLNMapView.styleURL`; overlay updates reassign
/// shapes on existing sources (cheap, no style reload).
///
/// Freeform gestures (pan/zoom/rotate) are explicitly enabled; a `camera`
/// command fits hole bounds with rotate-to-bearing only when it changes (token
/// bump), so it never fights the user's manual pan/zoom. An optional long-press
/// gesture (browse-mode "move tee") unprojects to a coordinate via
/// `onLongPress`, gated by `longPressEnabled`.
///
/// ```swift
/// CourseMapView(
///     configuration: CourseMapConfiguration(bundleDirectory: dir, manifest: manifest),
///     featuresGeoJSON: geojsonData,
///     overlays: MapOverlayState(distanceLine: [tee, pin], userLocation: .init(position: here)),
///     camera: .fitHole(holeBounds, bearing: holeBearing, token: holeNumber)
/// )
/// ```
public struct CourseMapView: UIViewRepresentable {
    public var configuration: CourseMapConfiguration
    public var featuresGeoJSON: Data
    public var overlays: MapOverlayState
    public var camera: MapCameraCommand?
    /// Imperative relative-zoom request. Applied once per change (token bump),
    /// independent of `camera` so a zoom-button tap never triggers a hole
    /// re-fit and never fights the hole-fit camera command.
    public var zoom: MapZoomCommand?
    /// Called on the main actor once the style finished loading (and again
    /// after any style rebuild caused by a configuration/features change).
    public var onMapReady: (() -> Void)?
    /// When true, a long-press on the map unprojects to a coordinate and calls
    /// `onLongPress`. Used for the browse-mode "move tee" gesture; false
    /// disables the recognizer so it never fires in GPS mode.
    public var longPressEnabled: Bool
    /// Called (main actor) with the unprojected WGS84 point of a long-press,
    /// only while `longPressEnabled` is true.
    public var onLongPress: ((LatLon) -> Void)?

    public init(
        configuration: CourseMapConfiguration,
        featuresGeoJSON: Data,
        overlays: MapOverlayState = .empty,
        camera: MapCameraCommand? = nil,
        zoom: MapZoomCommand? = nil,
        onMapReady: (() -> Void)? = nil,
        longPressEnabled: Bool = false,
        onLongPress: ((LatLon) -> Void)? = nil
    ) {
        self.configuration = configuration
        self.featuresGeoJSON = featuresGeoJSON
        self.overlays = overlays
        self.camera = camera
        self.zoom = zoom
        self.onMapReady = onMapReady
        self.longPressEnabled = longPressEnabled
        self.onLongPress = onLongPress
    }

    public func makeCoordinator() -> Coordinator {
        Coordinator()
    }

    public func makeUIView(context: Context) -> MLNMapView {
        buildMapView(coordinator: context.coordinator)
    }

    /// The `makeUIView` core, factored out so tests can drive it with a
    /// hand-made coordinator (SwiftUI's `Context` has no public initializer).
    func buildMapView(coordinator: Coordinator) -> MLNMapView {
        let styleURL = coordinator.writeStyleFile(
            configuration: configuration,
            featuresGeoJSON: featuresGeoJSON
        )
        // Never a zero frame — MapLibre's Metal setup SIGABRTs on a zero
        // drawable size. SwiftUI resizes the view before display.
        let mapView = MLNMapView(
            frame: CGRect(x: 0, y: 0, width: 390, height: 700),
            styleURL: styleURL
        )
        mapView.delegate = coordinator
        mapView.maximumZoomLevel = MapStyleBuilder.mapMaxZoom
        mapView.logoView.isHidden = true
        // GPS dot is fed via MapOverlayState, never MapLibre's own tracking.
        mapView.showsUserLocation = false
        // Explicitly (re-)enable freeform gestures. MapLibre defaults these on,
        // but we set them defensively to rule out a 6.27 default regression —
        // the camera is applied only on an explicit token bump (see
        // updateUIView), so it never fights the user's pan/zoom.
        mapView.isZoomEnabled = true
        mapView.isScrollEnabled = true
        mapView.isRotateEnabled = true
        mapView.isPitchEnabled = false // top-down course view; pitch adds nothing

        // Long-press → move active tee (browse mode). Recognizer stays attached
        // but is enabled/disabled per `longPressEnabled` in updateUIView.
        let longPress = UILongPressGestureRecognizer(
            target: coordinator,
            action: #selector(Coordinator.handleLongPress(_:))
        )
        longPress.isEnabled = longPressEnabled
        mapView.addGestureRecognizer(longPress)
        coordinator.longPressRecognizer = longPress
        coordinator.onLongPress = onLongPress

        coordinator.desiredOverlays = overlays
        coordinator.pendingCamera = camera
        coordinator.lastCameraCommand = camera
        // Seed the zoom baseline so the first real zoom command (a later token)
        // applies but an initial value never fires on mount.
        coordinator.lastZoomCommand = zoom
        coordinator.onMapReady = onMapReady
        return mapView
    }

    public func updateUIView(_ mapView: MLNMapView, context: Context) {
        applyUpdate(to: mapView, coordinator: context.coordinator)
    }

    /// The `updateUIView` core, factored out for the same testability reason as
    /// `buildMapView`.
    func applyUpdate(to mapView: MLNMapView, coordinator: Coordinator) {
        coordinator.onMapReady = onMapReady
        coordinator.onLongPress = onLongPress
        coordinator.longPressRecognizer?.isEnabled = longPressEnabled

        if coordinator.appliedConfiguration != configuration
            || coordinator.appliedFeaturesGeoJSON != featuresGeoJSON {
            let styleURL = coordinator.writeStyleFile(
                configuration: configuration,
                featuresGeoJSON: featuresGeoJSON
            )
            if let styleURL {
                coordinator.isStyleLoaded = false
                mapView.styleURL = styleURL
            }
        }

        coordinator.desiredOverlays = overlays
        if coordinator.isStyleLoaded, let style = mapView.style {
            MapOverlayRenderer.apply(overlays, to: style)
        }

        if let camera, camera != coordinator.lastCameraCommand {
            coordinator.lastCameraCommand = camera
            if coordinator.isStyleLoaded {
                Coordinator.applyCamera(camera, to: mapView)
            } else {
                coordinator.pendingCamera = camera
            }
        }

        // Relative zoom is applied imperatively on top of whatever center the
        // map currently has — it never touches `cameraCommand`, so a per-GPS-fix
        // updateUIView (which leaves `zoom` unchanged) won't re-fire it, and it
        // won't provoke a hole re-fit.
        if let zoom, zoom != coordinator.lastZoomCommand {
            coordinator.lastZoomCommand = zoom
            Coordinator.applyZoom(zoom, to: mapView)
        }
    }

    public static func dismantleUIView(_ uiView: MLNMapView, coordinator: Coordinator) {
        uiView.delegate = nil
        coordinator.removeStyleFile()
    }

    // MARK: - Coordinator

    @MainActor
    public final class Coordinator: NSObject, @preconcurrency MLNMapViewDelegate {
        var appliedConfiguration: CourseMapConfiguration?
        var appliedFeaturesGeoJSON: Data?
        var desiredOverlays: MapOverlayState = .empty
        var lastCameraCommand: MapCameraCommand?
        var lastZoomCommand: MapZoomCommand?
        var pendingCamera: MapCameraCommand?
        var isStyleLoaded = false
        var onMapReady: (() -> Void)?
        var onLongPress: ((LatLon) -> Void)?
        weak var longPressRecognizer: UILongPressGestureRecognizer?
        private var styleFileURL: URL?

        /// Unprojects the long-press point to a WGS84 coordinate and forwards
        /// it once, on gesture begin (a single place, not per drag frame — the
        /// simpler long-press-to-place interaction; see CourseMapView docs).
        @objc func handleLongPress(_ gesture: UILongPressGestureRecognizer) {
            guard gesture.state == .began,
                  let mapView = gesture.view as? MLNMapView,
                  let onLongPress else { return }
            let point = gesture.location(in: mapView)
            let coordinate = mapView.convert(point, toCoordinateFrom: mapView)
            onLongPress(LatLon(lat: coordinate.latitude, lon: coordinate.longitude))
        }

        /// Serializes the generated style to a fresh temp file (a new URL each
        /// time, so re-setting `MLNMapView.styleURL` always reloads). Returns
        /// nil — leaving the previous style in place — if generation fails
        /// (corrupt features GeoJSON).
        func writeStyleFile(configuration: CourseMapConfiguration, featuresGeoJSON: Data) -> URL? {
            appliedConfiguration = configuration
            appliedFeaturesGeoJSON = featuresGeoJSON
            do {
                let data = try MapStyleBuilder.styleJSONData(
                    configuration: configuration,
                    featuresGeoJSON: featuresGeoJSON
                )
                let url = FileManager.default.temporaryDirectory
                    .appending(path: "course-map-style-\(UUID().uuidString).json")
                try data.write(to: url, options: .atomic)
                removeStyleFile()
                styleFileURL = url
                return url
            } catch {
                assertionFailure("Course map style generation failed: \(error)")
                return nil
            }
        }

        func removeStyleFile() {
            if let styleFileURL {
                try? FileManager.default.removeItem(at: styleFileURL)
            }
            styleFileURL = nil
        }

        /// Applies a camera command. Exposed (internal) so tests can exercise
        /// the bbox-fit + bearing math against a real MLNMapView.
        static func applyCamera(_ command: MapCameraCommand, to mapView: MLNMapView) {
            switch command.target {
            case .bounds(let bounds):
                var corners = [
                    CLLocationCoordinate2D(latitude: bounds.south, longitude: bounds.west),
                    CLLocationCoordinate2D(latitude: bounds.south, longitude: bounds.east),
                    CLLocationCoordinate2D(latitude: bounds.north, longitude: bounds.east),
                    CLLocationCoordinate2D(latitude: bounds.north, longitude: bounds.west),
                ]
                let bbox = MLNPolygon(coordinates: &corners, count: UInt(corners.count))
                let inset = CGFloat(command.padding)
                let camera = mapView.cameraThatFitsShape(
                    bbox,
                    direction: command.bearing,
                    edgePadding: UIEdgeInsets(top: inset, left: inset, bottom: inset, right: inset)
                )
                mapView.setCamera(camera, animated: command.animated)
            case .center(let point, let zoom):
                mapView.setCenter(
                    point.clCoordinate,
                    zoomLevel: zoom,
                    direction: command.bearing,
                    animated: command.animated
                )
            }
        }

        /// Applies a relative zoom: bumps the map's current zoom level by
        /// `command.delta` (clamped to the map's min/max), keeping the current
        /// center. Independent of the hole-fit camera. Exposed (internal) so
        /// tests can exercise it against a real MLNMapView.
        static func applyZoom(_ command: MapZoomCommand, to mapView: MLNMapView) {
            let target = min(
                max(mapView.zoomLevel + command.delta, mapView.minimumZoomLevel),
                mapView.maximumZoomLevel
            )
            mapView.setZoomLevel(target, animated: command.animated)
        }

        // MARK: MLNMapViewDelegate

        public func mapView(_ mapView: MLNMapView, didFinishLoading style: MLNStyle) {
            isStyleLoaded = true
            MapOverlayRenderer.apply(desiredOverlays, to: style)
            if let pendingCamera {
                Self.applyCamera(pendingCamera, to: mapView)
                self.pendingCamera = nil
            }
            onMapReady?()
        }
    }
}
