import MapLibre
import SwiftUI

/// SwiftUI map view for one downloaded course bundle: offline ortho raster
/// basemap + course feature polygons (web editor palette) + dynamic overlays
/// (distance line, target markers, custom GPS dot).
///
/// Self-contained: everything comes in through the initializer — no app
/// environment. The style is generated by `MapStyleBuilder`, written to a
/// temp file, and loaded via `MLNMapView.styleURL`; overlay updates reassign
/// shapes on existing sources (cheap, no style reload).
///
/// Freeform gestures (pan/zoom/rotate) are explicitly enabled; a `camera`
/// command fits hole bounds with rotate-to-bearing only when it changes (token
/// bump), so it never fights the user's manual pan/zoom. An optional long-press
/// gesture (browse-mode "move tee") unprojects to a coordinate via
/// `onLongPress`, gated by `longPressEnabled`.
///
/// ```swift
/// CourseMapView(
///     configuration: CourseMapConfiguration(bundleDirectory: dir, manifest: manifest),
///     featuresGeoJSON: geojsonData,
///     overlays: MapOverlayState(distanceLine: [tee, pin], userLocation: .init(position: here)),
///     camera: .fitHole(holeBounds, bearing: holeBearing, token: holeNumber)
/// )
/// ```
public struct CourseMapView: UIViewRepresentable {
    public var configuration: CourseMapConfiguration
    public var featuresGeoJSON: Data
    public var overlays: MapOverlayState
    public var camera: MapCameraCommand?
    /// Imperative relative-zoom request. Applied once per change (token bump),
    /// independent of `camera` so a zoom-button tap never triggers a hole
    /// re-fit and never fights the hole-fit camera command.
    public var zoom: MapZoomCommand?
    /// Green-view analysis overlay (heat map + boundary + fall-line arrows);
    /// nil renders nothing. Applied via runtime source/layer add/remove — no
    /// style reload. Change detection is by (result identity, mode).
    public var analysis: GreenAnalysisMapState?
    /// Green-view putt-read overlay (break path, aim dot, reference line,
    /// ball/hole markers); nil renders nothing. Updates via cheap shape
    /// reassignment — it changes on every marker drag frame. The ball/hole
    /// markers also join the handle drag hit-test (ids
    /// `PuttOverlay.ballHandleID`/`.holeHandleID`) whenever `adjustEnabled`
    /// lets the drag recognizer run.
    public var putt: PuttReadGeometry.PuttOverlay?
    /// Called on the main actor once the style finished loading (and again
    /// after any style rebuild caused by a configuration/features change).
    public var onMapReady: (() -> Void)?
    /// Called (main actor) whenever the camera settles, with the current
    /// center (WGS84), zoom level, and bearing. Lets the model snapshot the
    /// user's view before a re-framing tool so it can be restored on exit.
    public var onCameraChange: ((LatLon, Double, Double) -> Void)?
    /// When true, a long-press on the map unprojects to a coordinate and calls
    /// `onLongPress`. Generic place-a-point gesture; the on-course screen's
    /// browse-mode "move tee" use of it is RETIRED (Adjust mode owns moves —
    /// the plain long-press recognized simultaneously with MapLibre's
    /// quick-zoom, so moving the tee also zoomed the map). Kept as an input
    /// for potential future use; no screen currently enables it.
    public var longPressEnabled: Bool
    /// Called (main actor) with the unprojected WGS84 point of a long-press,
    /// only while `longPressEnabled` is true.
    public var onLongPress: ((LatLon) -> Void)?
    /// When true, a single tap on the map unprojects to a coordinate and calls
    /// `onMeasureTap` (measure mode places a point). A dedicated UIKit
    /// recognizer — the SwiftUI immersive TapGesture is gated off separately
    /// while measure is active. Deferring to MapLibre's double-tap zoom keeps
    /// a quick double tap zooming instead of placing two stray points.
    public var measureTapEnabled: Bool
    /// Called (main actor) with the unprojected WGS84 point of a single tap,
    /// only while `measureTapEnabled` is true.
    public var onMeasureTap: ((LatLon) -> Void)?
    /// When true (Adjust mode), a short-press drag on one of
    /// `overlays.adjustHandles` grabs that handle and reports its movement
    /// through `onHandleGrab`/`onHandleMove`/`onHandleDrop`. The drag CLAIMS
    /// the touch: while a handle is grabbed the map's own pan/zoom/rotate are
    /// disabled (restored on release) and the recognizer's delegate refuses
    /// simultaneous recognition — so moving a handle can never also pan or
    /// quick-zoom the map (the old move-tee long-press bug).
    public var adjustEnabled: Bool
    /// When true (Adjust MODE, as opposed to green-view putt dragging), the
    /// map's gesture zoom + rotate are disabled for the whole mode: with a
    /// finger you routinely MISS the small handle, the drag never begins, and
    /// MapLibre's own quick-zoom fires instead ("zooms out when I tap Adjust").
    /// Green view keeps pinch zoom (a missed putt-marker grab just pans).
    public var adjustLocksGestures: Bool
    /// A handle was grabbed (drag began). Argument: the handle id.
    public var onHandleGrab: ((String) -> Void)?
    /// The grabbed handle moved; called per drag frame with the unprojected
    /// WGS84 position under the finger.
    public var onHandleMove: ((String, LatLon) -> Void)?
    /// The drag ended (finger up or gesture cancelled); the model should
    /// commit/persist the handle's current position.
    public var onHandleDrop: ((String) -> Void)?

    public init(
        configuration: CourseMapConfiguration,
        featuresGeoJSON: Data,
        overlays: MapOverlayState = .empty,
        camera: MapCameraCommand? = nil,
        zoom: MapZoomCommand? = nil,
        analysis: GreenAnalysisMapState? = nil,
        putt: PuttReadGeometry.PuttOverlay? = nil,
        onMapReady: (() -> Void)? = nil,
        onCameraChange: ((LatLon, Double, Double) -> Void)? = nil,
        longPressEnabled: Bool = false,
        onLongPress: ((LatLon) -> Void)? = nil,
        measureTapEnabled: Bool = false,
        onMeasureTap: ((LatLon) -> Void)? = nil,
        adjustEnabled: Bool = false,
        adjustLocksGestures: Bool = true,
        onHandleGrab: ((String) -> Void)? = nil,
        onHandleMove: ((String, LatLon) -> Void)? = nil,
        onHandleDrop: ((String) -> Void)? = nil
    ) {
        self.configuration = configuration
        self.featuresGeoJSON = featuresGeoJSON
        self.overlays = overlays
        self.camera = camera
        self.zoom = zoom
        self.analysis = analysis
        self.putt = putt
        self.onMapReady = onMapReady
        self.onCameraChange = onCameraChange
        self.longPressEnabled = longPressEnabled
        self.onLongPress = onLongPress
        self.measureTapEnabled = measureTapEnabled
        self.onMeasureTap = onMeasureTap
        self.adjustEnabled = adjustEnabled
        self.adjustLocksGestures = adjustLocksGestures
        self.onHandleGrab = onHandleGrab
        self.onHandleMove = onHandleMove
        self.onHandleDrop = onHandleDrop
    }

    public func makeCoordinator() -> Coordinator {
        Coordinator()
    }

    public func makeUIView(context: Context) -> MLNMapView {
        buildMapView(coordinator: context.coordinator)
    }

    /// The `makeUIView` core, factored out so tests can drive it with a
    /// hand-made coordinator (SwiftUI's `Context` has no public initializer).
    func buildMapView(coordinator: Coordinator) -> MLNMapView {
        let styleURL = coordinator.writeStyleFile(
            configuration: configuration,
            featuresGeoJSON: featuresGeoJSON
        )
        // Never a zero frame — MapLibre's Metal setup SIGABRTs on a zero
        // drawable size. SwiftUI resizes the view before display.
        let mapView = MLNMapView(
            frame: CGRect(x: 0, y: 0, width: 390, height: 700),
            styleURL: styleURL
        )
        mapView.delegate = coordinator
        mapView.maximumZoomLevel = MapStyleBuilder.mapMaxZoom
        mapView.logoView.isHidden = true
        // The camera commands own `contentInset` (it is how a tool's chrome —
        // hole header, bottom panel — is kept out of a bounds fit, see
        // `applyCamera`). MapLibre's own safe-area adjustment would fight that,
        // so it is off; the insets we pass already include the safe areas.
        mapView.automaticallyAdjustsContentInset = false
        // Drop the compass below the floating hole header (it appears whenever
        // the hole-fit camera has a bearing, and the default top-right slot is
        // behind the header).
        mapView.compassViewPosition = .topRight
        mapView.compassViewMargins = CGPoint(x: 12, y: 80)
        // GPS dot is fed via MapOverlayState, never MapLibre's own tracking.
        mapView.showsUserLocation = false
        // Explicitly (re-)enable freeform gestures. MapLibre defaults these on,
        // but we set them defensively to rule out a 6.27 default regression —
        // the camera is applied only on an explicit token bump (see
        // updateUIView), so it never fights the user's pan/zoom.
        mapView.isZoomEnabled = true
        mapView.isScrollEnabled = true
        mapView.isRotateEnabled = true
        mapView.isPitchEnabled = false // top-down course view; pitch adds nothing

        // Long-press → move active tee (browse mode). Recognizer stays attached
        // but is enabled/disabled per `longPressEnabled` in updateUIView.
        let longPress = UILongPressGestureRecognizer(
            target: coordinator,
            action: #selector(Coordinator.handleLongPress(_:))
        )
        longPress.isEnabled = longPressEnabled
        mapView.addGestureRecognizer(longPress)
        coordinator.longPressRecognizer = longPress
        coordinator.onLongPress = onLongPress

        // Single tap → place measure point (measure mode only). Sibling to the
        // long-press; deferred to MapLibre's own double-tap recognizers so a
        // double tap still zooms (and never places two points).
        let measureTap = UITapGestureRecognizer(
            target: coordinator,
            action: #selector(Coordinator.handleMeasureTap(_:))
        )
        measureTap.isEnabled = measureTapEnabled
        for recognizer in mapView.gestureRecognizers ?? [] {
            if let tap = recognizer as? UITapGestureRecognizer, tap.numberOfTapsRequired == 2 {
                measureTap.require(toFail: tap)
            }
        }
        mapView.addGestureRecognizer(measureTap)
        coordinator.measureTapRecognizer = measureTap
        coordinator.onMeasureTap = onMeasureTap

        // Short-press drag → move an Adjust handle. A long-press recognizer
        // with a short minimum press (grab) whose .changed states are the
        // drag. The coordinator is its delegate: `gestureRecognizerShouldBegin`
        // hit-tests the handles (no handle → the recognizer never begins and
        // the map pans normally) and simultaneous recognition with the map's
        // own recognizers is refused, so the drag owns the touch exclusively.
        let adjustPress = UILongPressGestureRecognizer(
            target: coordinator,
            action: #selector(Coordinator.handleAdjustPress(_:))
        )
        adjustPress.minimumPressDuration = Coordinator.adjustMinimumPressDuration
        // Grabbing is positional (the hit-test), not stillness — allow the
        // finger to wander during the brief press without failing the grab.
        adjustPress.allowableMovement = .greatestFiniteMagnitude
        adjustPress.delegate = coordinator
        adjustPress.isEnabled = adjustEnabled
        mapView.addGestureRecognizer(adjustPress)
        coordinator.adjustPressRecognizer = adjustPress
        coordinator.onHandleGrab = onHandleGrab
        coordinator.onHandleMove = onHandleMove
        coordinator.onHandleDrop = onHandleDrop

        coordinator.desiredOverlays = overlays
        coordinator.desiredAnalysis = analysis
        coordinator.desiredPutt = putt
        coordinator.pendingCamera = camera
        coordinator.lastCameraCommand = camera
        // Seed the zoom baseline so the first real zoom command (a later token)
        // applies but an initial value never fires on mount.
        coordinator.lastZoomCommand = zoom
        coordinator.onMapReady = onMapReady
        coordinator.onCameraChange = onCameraChange
        return mapView
    }

    public func updateUIView(_ mapView: MLNMapView, context: Context) {
        applyUpdate(to: mapView, coordinator: context.coordinator)
    }

    /// The `updateUIView` core, factored out for the same testability reason as
    /// `buildMapView`.
    func applyUpdate(to mapView: MLNMapView, coordinator: Coordinator) {
        coordinator.onMapReady = onMapReady
        coordinator.onCameraChange = onCameraChange
        coordinator.onLongPress = onLongPress
        coordinator.longPressRecognizer?.isEnabled = longPressEnabled
        coordinator.onMeasureTap = onMeasureTap
        coordinator.measureTapRecognizer?.isEnabled = measureTapEnabled
        coordinator.onHandleGrab = onHandleGrab
        coordinator.onHandleMove = onHandleMove
        coordinator.onHandleDrop = onHandleDrop
        // Disabling mid-drag cancels the recognizer → endHandleDrag restores
        // the map gestures (see handleAdjustPress .cancelled).
        coordinator.adjustPressRecognizer?.isEnabled = adjustEnabled
        // In Adjust mode, kill gesture zoom + rotate for the WHOLE mode, not
        // just during a successful grab. With a finger/mouse you routinely MISS
        // the small handle, so `gestureRecognizerShouldBegin` returns false, the
        // drag never begins, and MapLibre's own quick-zoom fires instead — the
        // "zooms out all the time" report. Pan stays on (reposition freely) and
        // the +/- buttons still zoom (imperative `setZoomLevel`, unaffected by
        // `isZoomEnabled`). Skipped while a drag is live so the per-drag scroll
        // disable in `beginHandleDrag` isn't stomped.
        // The mode-wide gesture lock applies only in Adjust mode proper — the
        // green view's putt-marker dragging keeps pinch zoom (see
        // `adjustLocksGestures`).
        let locksGestures = adjustEnabled && adjustLocksGestures
        if coordinator.draggedHandleID == nil {
            mapView.isZoomEnabled = !locksGestures
            mapView.isRotateEnabled = !locksGestures
            mapView.isScrollEnabled = true
        }

        if coordinator.appliedConfiguration != configuration
            || coordinator.appliedFeaturesGeoJSON != featuresGeoJSON {
            let styleURL = coordinator.writeStyleFile(
                configuration: configuration,
                featuresGeoJSON: featuresGeoJSON
            )
            if let styleURL {
                coordinator.isStyleLoaded = false
                mapView.styleURL = styleURL
            }
        }

        coordinator.desiredOverlays = overlays
        coordinator.desiredAnalysis = analysis
        coordinator.desiredPutt = putt
        if coordinator.isStyleLoaded, let style = mapView.style {
            MapOverlayRenderer.apply(overlays, to: style)
            coordinator.routeLegLabelRenderer.apply(overlays.routeLegLabels, to: mapView)
            coordinator.adjustHandleRenderer.apply(overlays.adjustHandles, to: style)
            coordinator.analysisRenderer.apply(analysis, to: style)
            // After analysis so the putt layers stack above the heat/arrows.
            coordinator.puttRenderer.apply(putt, to: style)
        }

        // Apply ONLY when the token changes. The command also carries the hole
        // bounds, derived from live furniture positions — so an Adjust move /
        // Reset hole / tee change alters the bounds WITHOUT a token bump, and
        // gating on `==` would re-fit (zoom) the map on every such edit. Only
        // deliberate re-frames (hole nav, recenter, Green view) bump the token.
        if let camera, camera.token != coordinator.lastCameraCommand?.token {
            coordinator.lastCameraCommand = camera
            if coordinator.isStyleLoaded {
                Coordinator.applyCamera(camera, to: mapView)
            } else {
                coordinator.pendingCamera = camera
            }
        }

        // Relative zoom is applied imperatively on top of whatever center the
        // map currently has — it never touches `cameraCommand`, so a per-GPS-fix
        // updateUIView (which leaves `zoom` unchanged) won't re-fire it, and it
        // won't provoke a hole re-fit.
        if let zoom, zoom != coordinator.lastZoomCommand {
            coordinator.lastZoomCommand = zoom
            Coordinator.applyZoom(zoom, to: mapView)
        }
    }

    public static func dismantleUIView(_ uiView: MLNMapView, coordinator: Coordinator) {
        uiView.delegate = nil
        coordinator.removeStyleFile()
    }

    // MARK: - Coordinator

    @MainActor
    public final class Coordinator: NSObject, @preconcurrency MLNMapViewDelegate,
        UIGestureRecognizerDelegate {
        var appliedConfiguration: CourseMapConfiguration?
        var appliedFeaturesGeoJSON: Data?
        var desiredOverlays: MapOverlayState = .empty
        var desiredAnalysis: GreenAnalysisMapState?
        var desiredPutt: PuttReadGeometry.PuttOverlay?
        let analysisRenderer = GreenAnalysisRenderer()
        let puttRenderer = PuttOverlayRenderer()
        let routeLegLabelRenderer = RouteLegLabelRenderer()
        let adjustHandleRenderer = AdjustHandleRenderer()
        var lastCameraCommand: MapCameraCommand?
        var lastZoomCommand: MapZoomCommand?
        var pendingCamera: MapCameraCommand?
        var isStyleLoaded = false
        var onMapReady: (() -> Void)?
        var onCameraChange: ((LatLon, Double, Double) -> Void)?
        var onLongPress: ((LatLon) -> Void)?
        weak var longPressRecognizer: UILongPressGestureRecognizer?
        var onMeasureTap: ((LatLon) -> Void)?
        weak var measureTapRecognizer: UITapGestureRecognizer?
        var onHandleGrab: ((String) -> Void)?
        var onHandleMove: ((String, LatLon) -> Void)?
        var onHandleDrop: ((String) -> Void)?
        weak var adjustPressRecognizer: UILongPressGestureRecognizer?
        /// The handle currently being dragged; nil = no drag in flight.
        private(set) var draggedHandleID: String?
        /// The map gesture flags saved when a drag disabled them, restored on
        /// release (defensive — they are all `true` in this app).
        private var savedGestureFlags: (scroll: Bool, zoom: Bool, rotate: Bool)?
        private var styleFileURL: URL?

        /// Short grab press: long enough that a plain pan never grabs, short
        /// enough to feel like picking the handle up.
        static let adjustMinimumPressDuration: TimeInterval = 0.18
        /// Screen-space grab radius around a handle center.
        static let adjustHitThreshold: CGFloat = 44

        /// Unprojects the long-press point to a WGS84 coordinate and forwards
        /// it once, on gesture begin (a single place, not per drag frame — the
        /// simpler long-press-to-place interaction; see CourseMapView docs).
        @objc func handleLongPress(_ gesture: UILongPressGestureRecognizer) {
            guard gesture.state == .began,
                  let mapView = gesture.view as? MLNMapView,
                  let onLongPress else { return }
            let point = gesture.location(in: mapView)
            let coordinate = mapView.convert(point, toCoordinateFrom: mapView)
            onLongPress(LatLon(lat: coordinate.latitude, lon: coordinate.longitude))
        }

        /// Unprojects a single tap to a WGS84 coordinate → place a measure
        /// point. Only fires while measure mode enables the recognizer.
        @objc func handleMeasureTap(_ gesture: UITapGestureRecognizer) {
            guard gesture.state == .ended,
                  let mapView = gesture.view as? MLNMapView,
                  let onMeasureTap else { return }
            let point = gesture.location(in: mapView)
            let coordinate = mapView.convert(point, toCoordinateFrom: mapView)
            onMeasureTap(LatLon(lat: coordinate.latitude, lon: coordinate.longitude))
        }

        // MARK: Adjust-handle drag

        /// The Adjust drag gesture. `.began` only ever fires on a handle hit —
        /// `gestureRecognizerShouldBegin` already hit-tested, so a press on
        /// empty map never begins and never disturbs the map's own gestures.
        @objc func handleAdjustPress(_ gesture: UILongPressGestureRecognizer) {
            guard let mapView = gesture.view as? MLNMapView else { return }
            let point = gesture.location(in: mapView)
            switch gesture.state {
            case .began:
                beginHandleDrag(at: point, in: mapView)
            case .changed:
                continueHandleDrag(at: point, in: mapView)
            case .ended:
                continueHandleDrag(at: point, in: mapView)
                endHandleDrag(in: mapView)
            case .cancelled, .failed:
                endHandleDrag(in: mapView)
            default:
                break
            }
        }

        /// Nearest handle id within `adjustHitThreshold` screen points of
        /// `point`, or nil. Projects each handle via
        /// `convert(coordinate:toPointTo:)` so the test is in stable screen
        /// space regardless of zoom. Adjust handles and the green view's putt
        /// ball/hole markers share the hit-test (they are never present
        /// together — Adjust mode and Green view are mutually exclusive).
        func nearestHandle(to point: CGPoint, in mapView: MLNMapView) -> String? {
            var candidates: [(id: String, position: LatLon)] = desiredOverlays.adjustHandles
                .map { ($0.id, $0.position) }
            if let putt = desiredPutt {
                if let ball = putt.ball {
                    candidates.append((PuttReadGeometry.PuttOverlay.ballHandleID, ball))
                }
                if let hole = putt.hole {
                    candidates.append((PuttReadGeometry.PuttOverlay.holeHandleID, hole))
                }
            }
            var best: (id: String, distance: CGFloat)?
            for handle in candidates {
                let projected = mapView.convert(handle.position.clCoordinate, toPointTo: mapView)
                let distance = hypot(projected.x - point.x, projected.y - point.y)
                if distance <= Self.adjustHitThreshold, distance < (best?.distance ?? .infinity) {
                    best = (handle.id, distance)
                }
            }
            return best?.id
        }

        /// Grab: claim the touch. Disables the map's pan/zoom/rotate for the
        /// duration of the drag — combined with the delegate's refusal of
        /// simultaneous recognition, this is what stops MapLibre's own
        /// long-press/quick-zoom from firing alongside the move (the old
        /// move-tee bug where moving the tee also zoomed the map). Returns
        /// false (and touches nothing) when no handle is within the threshold.
        /// Exposed (internal) so tests can drive the state machine directly —
        /// real finger drags aren't scriptable.
        @discardableResult
        func beginHandleDrag(at point: CGPoint, in mapView: MLNMapView) -> Bool {
            guard draggedHandleID == nil,
                  let id = nearestHandle(to: point, in: mapView) else { return false }
            draggedHandleID = id
            savedGestureFlags = (mapView.isScrollEnabled, mapView.isZoomEnabled, mapView.isRotateEnabled)
            mapView.isScrollEnabled = false
            mapView.isZoomEnabled = false
            mapView.isRotateEnabled = false
            onHandleGrab?(id)
            return true
        }

        /// Drag frame: unproject the touch and report the live position.
        func continueHandleDrag(at point: CGPoint, in mapView: MLNMapView) {
            guard let id = draggedHandleID else { return }
            let coordinate = mapView.convert(point, toCoordinateFrom: mapView)
            onHandleMove?(id, LatLon(lat: coordinate.latitude, lon: coordinate.longitude))
        }

        /// Release: restore the map gestures and let the model commit.
        func endHandleDrag(in mapView: MLNMapView) {
            guard let id = draggedHandleID else { return }
            draggedHandleID = nil
            if let saved = savedGestureFlags {
                mapView.isScrollEnabled = saved.scroll
                mapView.isZoomEnabled = saved.zoom
                mapView.isRotateEnabled = saved.rotate
            }
            savedGestureFlags = nil
            onHandleDrop?(id)
        }

        // MARK: UIGestureRecognizerDelegate (adjust drag only)

        /// Hit-test BEFORE recognition: a press that lands on no handle never
        /// begins, so the map's own pan/pinch stay untouched ("miss = the map
        /// pans"). Only the adjust recognizer has this coordinator as its
        /// delegate.
        public func gestureRecognizerShouldBegin(_ gestureRecognizer: UIGestureRecognizer) -> Bool {
            guard gestureRecognizer === adjustPressRecognizer,
                  let mapView = gestureRecognizer.view as? MLNMapView else { return true }
            return nearestHandle(to: gestureRecognizer.location(in: mapView), in: mapView) != nil
        }

        /// The drag claims the gesture exclusively: never recognize together
        /// with the map's pan/pinch/rotate/quick-zoom recognizers. (The old
        /// move-tee long-press had no delegate, so MapLibre's quick-zoom fired
        /// simultaneously and the map zoomed while the tee moved.)
        public func gestureRecognizer(
            _ gestureRecognizer: UIGestureRecognizer,
            shouldRecognizeSimultaneouslyWith otherGestureRecognizer: UIGestureRecognizer
        ) -> Bool {
            false
        }

        /// Serializes the generated style to a fresh temp file (a new URL each
        /// time, so re-setting `MLNMapView.styleURL` always reloads). Returns
        /// nil — leaving the previous style in place — if generation fails
        /// (corrupt features GeoJSON).
        func writeStyleFile(configuration: CourseMapConfiguration, featuresGeoJSON: Data) -> URL? {
            appliedConfiguration = configuration
            appliedFeaturesGeoJSON = featuresGeoJSON
            do {
                let data = try MapStyleBuilder.styleJSONData(
                    configuration: configuration,
                    featuresGeoJSON: featuresGeoJSON,
                    orthoTileExtension: MapStyleBuilder.detectOrthoExtension(
                        bundleDirectory: configuration.bundleDirectory
                    )
                )
                let url = FileManager.default.temporaryDirectory
                    .appending(path: "course-map-style-\(UUID().uuidString).json")
                try data.write(to: url, options: .atomic)
                removeStyleFile()
                styleFileURL = url
                return url
            } catch {
                assertionFailure("Course map style generation failed: \(error)")
                return nil
            }
        }

        func removeStyleFile() {
            if let styleFileURL {
                try? FileManager.default.removeItem(at: styleFileURL)
            }
            styleFileURL = nil
        }

        /// Applies a camera command. Exposed (internal) so tests can exercise
        /// the bbox-fit + bearing math against a real MLNMapView.
        static func applyCamera(_ command: MapCameraCommand, to mapView: MLNMapView) {
            // The chrome covering the map (hole header, tool panel) is handled in
            // two halves, because MapLibre splits the job:
            //   * ZOOM — `cameraThatFitsShape`'s edge padding shrinks the box the
            //     shape has to fit into, but it still CENTERS the shape on the
            //     full viewport (half of it behind the panel).
            //   * CENTER — `contentInset` moves the map's center point, so the
            //     shape lands centered in the part of the map you can see.
            // The fit is computed with the inset zeroed and the inset applied
            // after, so the offset is applied exactly once. Commands with no
            // insets reset it — exiting a tool restores full-viewport framing.
            let inset = UIEdgeInsets(
                top: CGFloat(command.insets.top),
                left: CGFloat(command.insets.left),
                bottom: CGFloat(command.insets.bottom),
                right: CGFloat(command.insets.right)
            )
            switch command.target {
            case .bounds(let bounds):
                fit(
                    [
                        LatLon(lat: bounds.south, lon: bounds.west),
                        LatLon(lat: bounds.south, lon: bounds.east),
                        LatLon(lat: bounds.north, lon: bounds.east),
                        LatLon(lat: bounds.north, lon: bounds.west),
                    ],
                    command: command, inset: inset, in: mapView
                )
            case .shape(let ring):
                fit(ring, command: command, inset: inset, in: mapView)
            case .center(let point, let zoom):
                mapView.setContentInset(inset, animated: false, completionHandler: nil)
                mapView.setCenter(
                    point.clCoordinate,
                    zoomLevel: zoom,
                    direction: command.bearing,
                    animated: command.animated
                )
            }
        }

        /// Frames a WGS84 ring: zoom from the fit (edge padding = the uniform
        /// padding + the chrome insets), center from `contentInset`. The fit is
        /// computed with the inset zeroed so the center offset is applied once,
        /// not twice.
        private static func fit(
            _ ring: [LatLon],
            command: MapCameraCommand,
            inset: UIEdgeInsets,
            in mapView: MLNMapView
        ) {
            guard ring.count >= 3 else { return }
            var coordinates = ring.map(\.clCoordinate)
            let shape = MLNPolygon(coordinates: &coordinates, count: UInt(coordinates.count))
            let base = CGFloat(command.padding)
            mapView.contentInset = .zero
            let camera = mapView.cameraThatFitsShape(
                shape,
                direction: command.bearing,
                edgePadding: UIEdgeInsets(
                    top: base + inset.top,
                    left: base + inset.left,
                    bottom: base + inset.bottom,
                    right: base + inset.right
                )
            )
            mapView.setContentInset(inset, animated: false, completionHandler: nil)
            mapView.setCamera(camera, animated: command.animated)
        }

        /// Applies a relative zoom: bumps the map's current zoom level by
        /// `command.delta` (clamped to the map's min/max), keeping the current
        /// center. Independent of the hole-fit camera. Exposed (internal) so
        /// tests can exercise it against a real MLNMapView.
        static func applyZoom(_ command: MapZoomCommand, to mapView: MLNMapView) {
            let target = min(
                max(mapView.zoomLevel + command.delta, mapView.minimumZoomLevel),
                mapView.maximumZoomLevel
            )
            mapView.setZoomLevel(target, animated: command.animated)
        }

        // MARK: MLNMapViewDelegate

        public func mapView(_ mapView: MLNMapView, didFinishLoading style: MLNStyle) {
            isStyleLoaded = true
            MapOverlayRenderer.apply(desiredOverlays, to: style)
            // A (re)loaded style starts without the runtime-registered label
            // images and analysis layers.
            routeLegLabelRenderer.styleDidReload()
            routeLegLabelRenderer.apply(desiredOverlays.routeLegLabels, to: mapView)
            adjustHandleRenderer.styleDidReload()
            adjustHandleRenderer.apply(desiredOverlays.adjustHandles, to: style)
            analysisRenderer.styleDidReload()
            analysisRenderer.apply(desiredAnalysis, to: style)
            puttRenderer.styleDidReload()
            puttRenderer.apply(desiredPutt, to: style)
            if let pendingCamera {
                Self.applyCamera(pendingCamera, to: mapView)
                self.pendingCamera = nil
            }
            onMapReady?()
        }

        /// As the camera moves, re-anchor route-leg labels so one whose midpoint
        /// scrolls off-screen is pulled onto the visible part of its leg.
        public func mapViewRegionIsChanging(_ mapView: MLNMapView) {
            routeLegLabelRenderer.reposition(in: mapView)
        }

        public func mapView(_ mapView: MLNMapView, regionDidChangeAnimated animated: Bool) {
            routeLegLabelRenderer.reposition(in: mapView)
            let center = mapView.centerCoordinate
            onCameraChange?(
                LatLon(lat: center.latitude, lon: center.longitude),
                mapView.zoomLevel,
                mapView.direction
            )
        }
    }
}
