import MapLibre
import SwiftUI

/// SwiftUI map view for one downloaded course bundle: offline ortho raster
/// basemap + course feature polygons (web editor palette) + dynamic overlays
/// (distance line, target markers, custom GPS dot).
///
/// Self-contained: everything comes in through the initializer — no app
/// environment. The style is generated by `MapStyleBuilder`, written to a
/// temp file, and loaded via `MLNMapView.styleURL`; overlay updates reassign
/// shapes on existing sources (cheap, no style reload).
///
/// Default gestures (pan/zoom/rotate) stay enabled; a `camera` command fits
/// hole bounds with rotate-to-bearing when the SwiftUI layer sets one.
///
/// ```swift
/// CourseMapView(
///     configuration: CourseMapConfiguration(bundleDirectory: dir, manifest: manifest),
///     featuresGeoJSON: geojsonData,
///     overlays: MapOverlayState(distanceLine: [tee, pin], userLocation: .init(position: here)),
///     camera: .fitHole(holeBounds, bearing: holeBearing, token: holeNumber)
/// )
/// ```
public struct CourseMapView: UIViewRepresentable {
    public var configuration: CourseMapConfiguration
    public var featuresGeoJSON: Data
    public var overlays: MapOverlayState
    public var camera: MapCameraCommand?
    /// Called on the main actor once the style finished loading (and again
    /// after any style rebuild caused by a configuration/features change).
    public var onMapReady: (() -> Void)?

    public init(
        configuration: CourseMapConfiguration,
        featuresGeoJSON: Data,
        overlays: MapOverlayState = .empty,
        camera: MapCameraCommand? = nil,
        onMapReady: (() -> Void)? = nil
    ) {
        self.configuration = configuration
        self.featuresGeoJSON = featuresGeoJSON
        self.overlays = overlays
        self.camera = camera
        self.onMapReady = onMapReady
    }

    public func makeCoordinator() -> Coordinator {
        Coordinator()
    }

    public func makeUIView(context: Context) -> MLNMapView {
        let coordinator = context.coordinator
        let styleURL = coordinator.writeStyleFile(
            configuration: configuration,
            featuresGeoJSON: featuresGeoJSON
        )
        // Never a zero frame — MapLibre's Metal setup SIGABRTs on a zero
        // drawable size. SwiftUI resizes the view before display.
        let mapView = MLNMapView(
            frame: CGRect(x: 0, y: 0, width: 390, height: 700),
            styleURL: styleURL
        )
        mapView.delegate = coordinator
        mapView.maximumZoomLevel = MapStyleBuilder.mapMaxZoom
        mapView.logoView.isHidden = true
        // GPS dot is fed via MapOverlayState, never MapLibre's own tracking.
        mapView.showsUserLocation = false

        coordinator.desiredOverlays = overlays
        coordinator.pendingCamera = camera
        coordinator.lastCameraCommand = camera
        coordinator.onMapReady = onMapReady
        return mapView
    }

    public func updateUIView(_ mapView: MLNMapView, context: Context) {
        let coordinator = context.coordinator
        coordinator.onMapReady = onMapReady

        if coordinator.appliedConfiguration != configuration
            || coordinator.appliedFeaturesGeoJSON != featuresGeoJSON {
            let styleURL = coordinator.writeStyleFile(
                configuration: configuration,
                featuresGeoJSON: featuresGeoJSON
            )
            if let styleURL {
                coordinator.isStyleLoaded = false
                mapView.styleURL = styleURL
            }
        }

        coordinator.desiredOverlays = overlays
        if coordinator.isStyleLoaded, let style = mapView.style {
            MapOverlayRenderer.apply(overlays, to: style)
        }

        if let camera, camera != coordinator.lastCameraCommand {
            coordinator.lastCameraCommand = camera
            if coordinator.isStyleLoaded {
                Coordinator.applyCamera(camera, to: mapView)
            } else {
                coordinator.pendingCamera = camera
            }
        }
    }

    public static func dismantleUIView(_ uiView: MLNMapView, coordinator: Coordinator) {
        uiView.delegate = nil
        coordinator.removeStyleFile()
    }

    // MARK: - Coordinator

    @MainActor
    public final class Coordinator: NSObject, @preconcurrency MLNMapViewDelegate {
        var appliedConfiguration: CourseMapConfiguration?
        var appliedFeaturesGeoJSON: Data?
        var desiredOverlays: MapOverlayState = .empty
        var lastCameraCommand: MapCameraCommand?
        var pendingCamera: MapCameraCommand?
        var isStyleLoaded = false
        var onMapReady: (() -> Void)?
        private var styleFileURL: URL?

        /// Serializes the generated style to a fresh temp file (a new URL each
        /// time, so re-setting `MLNMapView.styleURL` always reloads). Returns
        /// nil — leaving the previous style in place — if generation fails
        /// (corrupt features GeoJSON).
        func writeStyleFile(configuration: CourseMapConfiguration, featuresGeoJSON: Data) -> URL? {
            appliedConfiguration = configuration
            appliedFeaturesGeoJSON = featuresGeoJSON
            do {
                let data = try MapStyleBuilder.styleJSONData(
                    configuration: configuration,
                    featuresGeoJSON: featuresGeoJSON
                )
                let url = FileManager.default.temporaryDirectory
                    .appending(path: "course-map-style-\(UUID().uuidString).json")
                try data.write(to: url, options: .atomic)
                removeStyleFile()
                styleFileURL = url
                return url
            } catch {
                assertionFailure("Course map style generation failed: \(error)")
                return nil
            }
        }

        func removeStyleFile() {
            if let styleFileURL {
                try? FileManager.default.removeItem(at: styleFileURL)
            }
            styleFileURL = nil
        }

        /// Applies a camera command. Exposed (internal) so tests can exercise
        /// the bbox-fit + bearing math against a real MLNMapView.
        static func applyCamera(_ command: MapCameraCommand, to mapView: MLNMapView) {
            switch command.target {
            case .bounds(let bounds):
                var corners = [
                    CLLocationCoordinate2D(latitude: bounds.south, longitude: bounds.west),
                    CLLocationCoordinate2D(latitude: bounds.south, longitude: bounds.east),
                    CLLocationCoordinate2D(latitude: bounds.north, longitude: bounds.east),
                    CLLocationCoordinate2D(latitude: bounds.north, longitude: bounds.west),
                ]
                let bbox = MLNPolygon(coordinates: &corners, count: UInt(corners.count))
                let inset = CGFloat(command.padding)
                let camera = mapView.cameraThatFitsShape(
                    bbox,
                    direction: command.bearing,
                    edgePadding: UIEdgeInsets(top: inset, left: inset, bottom: inset, right: inset)
                )
                mapView.setCamera(camera, animated: command.animated)
            case .center(let point, let zoom):
                mapView.setCenter(
                    point.clCoordinate,
                    zoomLevel: zoom,
                    direction: command.bearing,
                    animated: command.animated
                )
            }
        }

        // MARK: MLNMapViewDelegate

        public func mapView(_ mapView: MLNMapView, didFinishLoading style: MLNStyle) {
            isStyleLoaded = true
            MapOverlayRenderer.apply(desiredOverlays, to: style)
            if let pendingCamera {
                Self.applyCamera(pendingCamera, to: mapView)
                self.pendingCamera = nil
            }
            onMapReady?()
        }
    }
}
